In [1]:
import sys
import pandas as pd
pd.options.display.max_colwidth = 600

sys.path.append('/Users/BKieft/Metabolomics/metatlas2/metatlas2')
import logging_config as lcf
import logging
import workflow_objects as wfo
import load_tools as ldt

In [2]:
# Set up logging with level
log_level = logging.INFO
lcf.setup_logging(log_level=log_level)
logger = lcf.get_logger('targeted_workflow', log_level=log_level)

In [3]:
# Load configuration files
ANALYSIS_CONFIG = ldt.load_metatlas2_config("/Users/BKieft/Metabolomics/metatlas2/configs/analysis.yaml")

2026-02-24 15:20:31 | metatlas2.load_tools | INFO | Loaded metatlas2 configuration from /Users/BKieft/Metabolomics/metatlas2/configs/analysis.yaml

In [4]:
# Set up analysis parameters
PROJECT_NAME = "20260106_JGI_LP-AC_510770_StrigoArab_final_EXP120B_HILICZ_USHXG03402"

ANALYSIS_ATLAS = "atl-rta-istd-hilicz-pos-b257289871514b8fb0cf03d4a9104b0e"

RT_ALIGN_NUM = 0
ANALYSIS_NUM = 1

In [5]:
# Auto Identifications
wfo.run_auto_identification(
    config=ANALYSIS_CONFIG,
    project_name=PROJECT_NAME,
    rt_alignment_number=RT_ALIGN_NUM,
    analysis_number=ANALYSIS_NUM,
    analysis_atlas=ANALYSIS_ATLAS
)

2026-02-24 15:20:31 | metatlas2.workflow_objects | INFO | Setting up AutoIdentification object for RT alignment number 0, analysis number 1...
2026-02-24 15:20:31 | metatlas2.workflow_objects | INFO | Setting up workflow paths...
2026-02-24 15:20:31 | metatlas2.workflow_objects | INFO | Checking for existing Auto Identification results within RT Alignment number 0 and analysis number 1...
2026-02-24 15:20:31 | metatlas2.database_interact | INFO | No existing AutoIdentification results found for RT alignment number 0 and analysis number 1. Proceeding.
2026-02-24 15:20:31 | metatlas2.workflow_objects | INFO | Retrieving all LCMS runs for project...
2026-02-24 15:20:31 | metatlas2.database_interact | INFO | Retrieved 34 LC/MS run files from database with filters: file_types=None, chromatography=None, polarity=None, format=parquet
2026-02-24 15:20:31 | metatlas2.workflow_objects | INFO | Loading atlas with UID atl-rta-istd-hilicz-pos-b257289871514b8fb0cf03d4a9104b0e from database...
2026-02-24 15:20:31 | metatlas2.database_interact | INFO | Attached main database for compound metadata
2026-02-24 15:20:31 | metatlas2.database_interact | INFO | Retrieved 65 compounds for atlas atl-rta-istd-hilicz-pos-b257289871514b8fb0cf03d4a9104b0e (Default HILICZ ISTD Atlas Positive (RT aligned))

,atlas_uid,atlas_name,atlas_description,chromatography,polarity,analysis_type,atlas_type,compound_uid,compound_name,inchi_key,...,adduct,mz,rt_peak,rt_min,rt_max,mz_tolerance,mz_rt_uid,rt_alignment_applied,manual_curation_applied,label
0,atl-rta-istd-hilicz-pos-b257289871514b8fb0cf03d4a9104b0e,Default HILICZ ISTD Atlas Positive (RT aligned),RT-aligned version of Default HILICZ ISTD Atlas Positive,HILICZ,POS,ISTD,RT-ALIGNED,cmp-029931c701334d928afd489a515199be,ABMBA (unlabeled),LCMZECCEEOQWLQ-UHFFFAOYSA-N,...,[M+H]+,229.981094,1.227322,0.959749,1.495809,5.0,mzrt-exp-c193b0938c354ee7ba3a3f3832a78626,True,False,ABMBA (unlabeled)
1,atl-rta-istd-hilicz-pos-b257289871514b8fb0cf03d4a9104b0e,Default HILICZ ISTD Atlas Positive (RT aligned),RT-aligned version of Default HILICZ ISTD Atlas Positive,HILICZ,POS,ISTD,RT-ALIGNED,cmp-d90c2db5ef4c4d32936770f670d9e445,nicotinamide (U - 13C),DFPAKSUCGFBDDF-IDEBNGHGSA-N,...,[M+H]+,129.075424,1.274494,1.006760,1.543142,5.0,mzrt-exp-d598c0759b7442c78672f248609e9808,True,False,nicotinamide (U - 13C)
2,atl-rta-istd-hilicz-pos-b257289871514b8fb0cf03d4a9104b0e,Default HILICZ ISTD Atlas Positive (RT aligned),RT-aligned version of Default HILICZ ISTD Atlas Positive,HILICZ,POS,ISTD,RT-ALIGNED,cmp-3f595e5966804f9c8b218e19d22ccd1b,nicotinamide (unlabeled),DFPAKSUCGFBDDF-UHFFFAOYSA-N,...,[M+H]+,123.055290,1.274494,1.006760,1.543142,5.0,mzrt-exp-678ac62b3fb04cfda5aaec04973a5cd5,True,False,nicotinamide (unlabeled)
3,atl-rta-istd-hilicz-pos-b257289871514b8fb0cf03d4a9104b0e,Default HILICZ ISTD Atlas Positive (RT aligned),RT-aligned version of Default HILICZ ISTD Atlas Positive,HILICZ,POS,ISTD,RT-ALIGNED,cmp-ab14a89034654984912986de1f8109e2,"thymine (U - 13C, 15N)",RWQNBRDOKXIBIV-BNUYUSEDSA-N,...,[M+H]+,134.061035,1.371676,1.103612,1.640656,5.0,mzrt-exp-b022966a1a6641f08ebe44734761397e,True,False,"thymine (U - 13C, 15N)"
4,atl-rta-istd-hilicz-pos-b257289871514b8fb0cf03d4a9104b0e,Default HILICZ ISTD Atlas Positive (RT aligned),RT-aligned version of Default HILICZ ISTD Atlas Positive,HILICZ,POS,ISTD,RT-ALIGNED,cmp-9b2629c670e044dabab1aaa9dbefb768,thymine (unlabeled),RWQNBRDOKXIBIV-UHFFFAOYSA-N,...,[M+H]+,127.050201,1.371676,1.103612,1.640656,5.0,mzrt-exp-0b2e2491ae4545cf8187549fc8b20600,True,False,thymine (unlabeled)

2026-02-24 15:20:31 | metatlas2.workflow_objects | INFO | Validating atlas Default HILICZ ISTD Atlas Positive (RT aligned) (UID: atl-rta-istd-hilicz-pos-b257289871514b8fb0cf03d4a9104b0e) with 65 compounds...
2026-02-24 15:20:31 | metatlas2.workflow_objects | INFO | Atlas passed validation!
2026-02-24 15:20:31 | metatlas2.workflow_objects | INFO | Loading workflow parameters for targeted analysis from config...
2026-02-24 15:20:31 | metatlas2.workflow_objects | INFO | Finding LCMSRuns matching criteria for auto-identification...
2026-02-24 15:20:31 | metatlas2.lcmsruns_tools | INFO | Filtering 34 LCMS runs with parameters: file_type=['experimental', 'istd', 'exctrl'], file_format=parquet, chromatography=HILIC, polarity=positive...
2026-02-24 15:20:31 | metatlas2.lcmsruns_tools | INFO | Filtered to 13 out of 34 total files.
2026-02-24 15:20:31 | metatlas2.workflow_objects | INFO | Passing Atlas and LCMSRuns to data extractor...
2026-02-24 15:20:31 | metatlas2.extract_data_from_parquet | INFO | Starting data extraction based on atl-rta-istd-hilicz-pos-b257289871514b8fb0cf03d4a9104b0e (Default HILICZ ISTD Atlas Positive (RT aligned)) for stage 'auto_identification' from 13 LCMS runs...
2026-02-24 15:20:31 | metatlas2.extract_data_from_parquet | INFO | Initiating an experimental data object to hold results during analysis...
2026-02-24 15:20:31 | metatlas2.extract_data_from_parquet | INFO | Starting data extraction for 65 compounds from 13 project files...
2026-02-24 15:20:31 | metatlas2.extract_data_from_parquet | INFO | Using ppm_tolerance=5.0 and extra_time=0.0 for data extraction.
2026-02-24 15:20:31 | metatlas2.extract_data_from_parquet | INFO | Using parallel processing with 8 workers...

Extracting data from parquet files:   0%|          | 0/13 [00:00<?, ?it/s]

2026-02-24 15:20:36 | metatlas2.workflow_objects | INFO | Passing ExperimentalData to MS2 hit finder...
2026-02-24 15:20:36 | metatlas2.load_tools | INFO | Loading reference spectra from /Users/BKieft/Metabolomics/metatlas_lite_data/databases/msms_refs/msms_refs_no_inosine15n.tab...
2026-02-24 15:20:36 | metatlas2.load_tools | INFO |     Number of total references: 1584
2026-02-24 15:20:36 | metatlas2.load_tools | INFO |     Number of unique InChI keys: 64
2026-02-24 15:20:36 | metatlas2.ms2_hit_detection | INFO | Finding MS2 hits using reference database with 1584 entries...
2026-02-24 15:20:36 | metatlas2.ms2_hit_detection | INFO | Prepared hit detection input for 56 files with MS2 data
2026-02-24 15:20:36 | metatlas2.ms2_hit_detection | INFO | Using parallel processing with 8 workers for hit detection...

Finding MS2 hits:   0%|          | 0/56 [00:00<?, ?it/s]

2026-02-24 15:20:41 | metatlas2.ms2_hit_detection | INFO | Hit detection complete: 56 compounds with reference hits and 2423 total hits
2026-02-24 15:20:41 | metatlas2.workflow_objects | INFO | Passing ExperimentalData and Atlas to ManualCuration creator...

Processing atlas compounds:   0%|          | 0/65 [00:00<?, ?compound/s]

2026-02-24 15:20:44 | metatlas2.workflow_objects | INFO | Passing AutoIdentification object to database saver...
2026-02-24 15:20:44 | metatlas2.database_interact | INFO | Preparing complete analysis data for database save...
2026-02-24 15:20:44 | metatlas2.database_interact | INFO | Checking for identical existing MS1 and MS2 summary records before database insert...
2026-02-24 15:20:44 | metatlas2.database_interact | INFO | Performing bulk database inserts...
2026-02-24 15:20:44 | metatlas2.database_interact | INFO | Inserting 65 compound metadata records...
2026-02-24 15:20:44 | metatlas2.database_interact | INFO | Inserting 2423 MS2 hits records...
2026-02-24 15:20:46 | metatlas2.database_interact | INFO | Inserting 9935 MS1 raw data records...
2026-02-24 15:20:49 | metatlas2.database_interact | INFO | Inserting 2992 MS2 raw data records...
2026-02-24 15:20:51 | metatlas2.database_interact | INFO | Compiling analysis summary for experimental data...
2026-02-24 15:20:51 | metatlas2.database_interact | INFO | Complete analysis data saved to database.

,inchi_key,adduct,MS1 datapoints,MS2 datapoints,MS2 hits
0,LCMZECCEEOQWLQ-UHFFFAOYSA-N,[M+H]+,447,199,150
1,DFPAKSUCGFBDDF-IDEBNGHGSA-N,[M+H]+,93,0,0
2,DFPAKSUCGFBDDF-UHFFFAOYSA-N,[M+H]+,177,0,0
3,RWQNBRDOKXIBIV-BNUYUSEDSA-N,[M+H]+,52,0,0
4,RWQNBRDOKXIBIV-UHFFFAOYSA-N,[M+H]+,11,0,0
...,...,...,...,...,...
60,LEVWYRKDKASIDU-IMJSIDKUSA-N,[M+H]+,0,0,0
61,ODKSFYDXXFIFQN-GZYYCROJSA-N,[M+H]+,140,70,33
62,ODKSFYDXXFIFQN-BYPYZUCNSA-N,[M+H]+,12,0,0
63,KDXKERNSBIXSRK-JMKXWGMHSA-N,[M+H]+,17,0,0
64,KDXKERNSBIXSRK-YFKPBYRVSA-N,[M+H]+,1,0,0