In [1]:
import sys
import pandas as pd
pd.options.display.max_colwidth = 300

sys.path.append('/Users/BKieft/Metabolomics/metatlas2/metatlas2')
import logging_config as lcf
import logging
import workflow_objects as wfo
import load_tools as ldt

In [2]:
# Set up logging with level
log_level = logging.INFO
lcf.setup_logging(log_level=log_level)
logger = lcf.get_logger('rt_alignment', log_level=log_level)

In [3]:
# Load configuration file
ANALYSIS_CONFIG = ldt.load_metatlas2_config("/Users/BKieft/Metabolomics/metatlas2/configs/analysis.yaml")

2026-02-23 13:16:22 | metatlas2.load_tools | INFO | Loaded metatlas2 configuration from /Users/BKieft/Metabolomics/metatlas2/configs/analysis.yaml

In [4]:
# Set up analysis parameters
PROJECT_NAME = "20260106_JGI_LP-AC_510770_StrigoArab_final_EXP120B_HILICZ_USHXG03402"
RT_ALIGN_CHROM = "HILICZ"
RT_ALIGN_NUM = 0

In [5]:
# RT Alignment
wfo.run_rt_alignment(
    config=ANALYSIS_CONFIG,
    project_name=PROJECT_NAME,
    rt_alignment_number=RT_ALIGN_NUM,
    chromatography=RT_ALIGN_CHROM
)

2026-02-23 13:16:22 | metatlas2.workflow_objects | INFO | Setting up RTAlign object for HILICZ chromatography and RT alignment number 0...
2026-02-23 13:16:22 | metatlas2.workflow_objects | INFO | Setting up workflow paths...
2026-02-23 13:16:22 | metatlas2.database_interact | INFO | Retrieved 34 LC/MS run files from database with filters: file_types=None, chromatography=None, polarity=None, format=parquet
2026-02-23 13:16:22 | metatlas2.lcmsruns_tools | INFO | Filtering 34 LCMS runs with parameters: file_type=['qc'], file_format=parquet, chromatography=HILIC, polarity=None...
2026-02-23 13:16:22 | metatlas2.lcmsruns_tools | INFO | Filtered to 4 out of 34 total files.
2026-02-23 13:16:22 | metatlas2.workflow_objects | INFO | Checking for existing RT model in database with UID atl-ref-qc-hilicz-pos-abe625936d724c77bc5162bc304767a7 (HILICZ) and RT Alignment number 0
2026-02-23 13:16:22 | metatlas2.database_interact | INFO | Retrieved and reconstructed RT alignment model rta-a0243b1cc0834fd785799f63d91805df (RT alignment number 0)
2026-02-23 13:16:22 | metatlas2.database_interact | INFO |   Model: polynomial (degree=2)
2026-02-23 13:16:22 | metatlas2.database_interact | INFO |   Performance: R²=0.9968, RMSE=0.3007
2026-02-23 13:16:22 | metatlas2.database_interact | INFO |   Training data: 4 QC files, 19 compounds
2026-02-23 13:16:22 | metatlas2.workflow_objects | INFO | Using the existing RT alignment model from database for atlas atl-ref-qc-hilicz-pos-abe625936d724c77bc5162bc304767a7 and RT alignment number 0.
2026-02-23 13:16:22 | metatlas2.workflow_objects | INFO | Loaded existing RT alignment model with R² = 0.9968, RMSE = 0.3007
2026-02-23 13:16:22 | metatlas2.rt_align_tools | INFO | Applying RT alignment model to target atlases and generating RT-aligned Atlas objects...
2026-02-23 13:16:22 | metatlas2.rt_align_tools | INFO | Loading HILICZ POS QC target atlas with UID atl-ref-qc-hilicz-pos-abe625936d724c77bc5162bc304767a7 for applying RT alignment model...
2026-02-23 13:16:22 | metatlas2.workflow_objects | INFO | Loading atlas with UID atl-ref-qc-hilicz-pos-abe625936d724c77bc5162bc304767a7 from database...
2026-02-23 13:16:22 | metatlas2.database_interact | INFO | Retrieved 20 compounds for atlas atl-ref-qc-hilicz-pos-abe625936d724c77bc5162bc304767a7 (Default HILICZ QC Atlas Positive)

,atlas_uid,atlas_name,atlas_description,chromatography,polarity,analysis_type,atlas_type,compound_uid,compound_name,inchi_key,...,adduct,mz,rt_peak,rt_min,rt_max,mz_tolerance,mz_rt_uid,rt_alignment_applied,manual_curation_applied,label
0,atl-ref-qc-hilicz-pos-abe625936d724c77bc5162bc304767a7,Default HILICZ QC Atlas Positive,Default QC compounds used for RT alignment,HILICZ,POS,QC,REFERENCE,cmp-029931c701334d928afd489a515199be,ABMBA (unlabeled),LCMZECCEEOQWLQ-UHFFFAOYSA-N,...,[M+H]+,229.981094,1.093806,0.793806,1.393806,5.0,mzrt-ref-761d0b117cb94cfb8fddc354010b4bdf,False,False,ABMBA (unlabeled)
1,atl-ref-qc-hilicz-pos-abe625936d724c77bc5162bc304767a7,Default HILICZ QC Atlas Positive,Default QC compounds used for RT alignment,HILICZ,POS,QC,REFERENCE,cmp-ab14a89034654984912986de1f8109e2,"thymine (U - 13C, 15N)",RWQNBRDOKXIBIV-BNUYUSEDSA-N,...,[M+H]+,134.061035,1.255231,0.955231,1.555231,5.0,mzrt-ref-62594c65801c494c999018d280e422ae,False,False,"thymine (U - 13C, 15N)"
2,atl-ref-qc-hilicz-pos-abe625936d724c77bc5162bc304767a7,Default HILICZ QC Atlas Positive,Default QC compounds used for RT alignment,HILICZ,POS,QC,REFERENCE,cmp-352256bace4045d09cc302c3f09efe00,adenine (U - 15N),GFFGJBXGBJISGV-CIKZIQIKSA-N,...,[M+H]+,141.046936,2.677602,2.377602,2.977602,5.0,mzrt-ref-8626a641ef6a477184b5dfef11fc716b,False,False,adenine (U - 15N)
3,atl-ref-qc-hilicz-pos-abe625936d724c77bc5162bc304767a7,Default HILICZ QC Atlas Positive,Default QC compounds used for RT alignment,HILICZ,POS,QC,REFERENCE,cmp-64416490823c4c6d8eec1d6e09bc173c,hypoxanthine (U - 15N),FDGQSTZJBFJUBT-NNZQUYKOSA-N,...,[M+H]+,141.033920,3.102967,2.802967,3.402967,5.0,mzrt-ref-cba1b0b7f9664046a5ec0f81ff52dfd1,False,False,hypoxanthine (U - 15N)
4,atl-ref-qc-hilicz-pos-abe625936d724c77bc5162bc304767a7,Default HILICZ QC Atlas Positive,Default QC compounds used for RT alignment,HILICZ,POS,QC,REFERENCE,cmp-dabffd9909104f439089fd4e91cc3fd6,inosine (U - 15N),UGQMRVRMYYASKQ-SHKQESLVSA-N,...,[M+H]+,273.076172,5.434236,5.134236,5.734236,5.0,mzrt-ref-0d14d49d68ef49ecb267f95a2f62797a,False,False,inosine (U - 15N)

2026-02-23 13:16:22 | metatlas2.workflow_objects | INFO | Validating atlas Default HILICZ QC Atlas Positive (UID: atl-ref-qc-hilicz-pos-abe625936d724c77bc5162bc304767a7) with 20 compounds...
2026-02-23 13:16:22 | metatlas2.workflow_objects | INFO | Atlas passed validation!
2026-02-23 13:16:22 | metatlas2.workflow_objects | INFO | Validating atlas Default HILICZ QC Atlas Positive (RT aligned) (UID: atl-rta-qc-hilicz-pos-1b28bd8beb0a4d239d29508f2e5a06d5) with 20 compounds...
2026-02-23 13:16:22 | metatlas2.workflow_objects | INFO | Atlas passed validation!
2026-02-23 13:16:22 | metatlas2.rt_align_tools | INFO | Loading HILICZ POS ISTD target atlas with UID atl-ref-istd-hilicz-pos-f7ee5d452c274c3caa794518f6db37bc for applying RT alignment model...
2026-02-23 13:16:22 | metatlas2.workflow_objects | INFO | Loading atlas with UID atl-ref-istd-hilicz-pos-f7ee5d452c274c3caa794518f6db37bc from database...
2026-02-23 13:16:22 | metatlas2.database_interact | INFO | Retrieved 65 compounds for atlas atl-ref-istd-hilicz-pos-f7ee5d452c274c3caa794518f6db37bc (Default HILICZ ISTD Atlas Positive)

,atlas_uid,atlas_name,atlas_description,chromatography,polarity,analysis_type,atlas_type,compound_uid,compound_name,inchi_key,...,adduct,mz,rt_peak,rt_min,rt_max,mz_tolerance,mz_rt_uid,rt_alignment_applied,manual_curation_applied,label
0,atl-ref-istd-hilicz-pos-f7ee5d452c274c3caa794518f6db37bc,Default HILICZ ISTD Atlas Positive,Default internal standard compounds used for checking performance,HILICZ,POS,ISTD,REFERENCE,cmp-029931c701334d928afd489a515199be,ABMBA (unlabeled),LCMZECCEEOQWLQ-UHFFFAOYSA-N,...,[M+H]+,229.981094,1.093806,0.793806,1.393806,5.0,mzrt-ref-761d0b117cb94cfb8fddc354010b4bdf,False,False,ABMBA (unlabeled)
1,atl-ref-istd-hilicz-pos-f7ee5d452c274c3caa794518f6db37bc,Default HILICZ ISTD Atlas Positive,Default internal standard compounds used for checking performance,HILICZ,POS,ISTD,REFERENCE,cmp-d90c2db5ef4c4d32936770f670d9e445,nicotinamide (U - 13C),DFPAKSUCGFBDDF-IDEBNGHGSA-N,...,[M+H]+,129.075424,1.146589,0.846589,1.446589,5.0,mzrt-ref-531a6b7a66484da690fcd7bb56b87ab6,False,False,nicotinamide (U - 13C)
2,atl-ref-istd-hilicz-pos-f7ee5d452c274c3caa794518f6db37bc,Default HILICZ ISTD Atlas Positive,Default internal standard compounds used for checking performance,HILICZ,POS,ISTD,REFERENCE,cmp-3f595e5966804f9c8b218e19d22ccd1b,nicotinamide (unlabeled),DFPAKSUCGFBDDF-UHFFFAOYSA-N,...,[M+H]+,123.055290,1.146589,0.846589,1.446589,5.0,mzrt-ref-b4136faf2c46467ca9b38bd9492c93fc,False,False,nicotinamide (unlabeled)
3,atl-ref-istd-hilicz-pos-f7ee5d452c274c3caa794518f6db37bc,Default HILICZ ISTD Atlas Positive,Default internal standard compounds used for checking performance,HILICZ,POS,ISTD,REFERENCE,cmp-ab14a89034654984912986de1f8109e2,"thymine (U - 13C, 15N)",RWQNBRDOKXIBIV-BNUYUSEDSA-N,...,[M+H]+,134.061035,1.255231,0.955231,1.555231,5.0,mzrt-ref-62594c65801c494c999018d280e422ae,False,False,"thymine (U - 13C, 15N)"
4,atl-ref-istd-hilicz-pos-f7ee5d452c274c3caa794518f6db37bc,Default HILICZ ISTD Atlas Positive,Default internal standard compounds used for checking performance,HILICZ,POS,ISTD,REFERENCE,cmp-9b2629c670e044dabab1aaa9dbefb768,thymine (unlabeled),RWQNBRDOKXIBIV-UHFFFAOYSA-N,...,[M+H]+,127.050201,1.255231,0.955231,1.555231,5.0,mzrt-ref-ee22525f790146bb8ee9d116d2b548d1,False,False,thymine (unlabeled)

2026-02-23 13:16:22 | metatlas2.workflow_objects | INFO | Validating atlas Default HILICZ ISTD Atlas Positive (UID: atl-ref-istd-hilicz-pos-f7ee5d452c274c3caa794518f6db37bc) with 65 compounds...
2026-02-23 13:16:22 | metatlas2.workflow_objects | INFO | Atlas passed validation!
2026-02-23 13:16:22 | metatlas2.workflow_objects | INFO | Validating atlas Default HILICZ ISTD Atlas Positive (RT aligned) (UID: atl-rta-istd-hilicz-pos-467e971e8ae14e7e93d55508cf5ef181) with 65 compounds...
2026-02-23 13:16:22 | metatlas2.workflow_objects | INFO | Atlas passed validation!
2026-02-23 13:16:22 | metatlas2.rt_align_tools | INFO | Loading HILICZ POS EMA target atlas with UID atl-ref-ema-hilicz-pos-9fc8b14f2ecb4f4086b0ff36b93ce062 for applying RT alignment model...
2026-02-23 13:16:22 | metatlas2.workflow_objects | INFO | Loading atlas with UID atl-ref-ema-hilicz-pos-9fc8b14f2ecb4f4086b0ff36b93ce062 from database...
2026-02-23 13:16:22 | metatlas2.database_interact | INFO | Retrieved 573 compounds for atlas atl-ref-ema-hilicz-pos-9fc8b14f2ecb4f4086b0ff36b93ce062 (Default HILICZ EMA Atlas Positive)

,atlas_uid,atlas_name,atlas_description,chromatography,polarity,analysis_type,atlas_type,compound_uid,compound_name,inchi_key,...,adduct,mz,rt_peak,rt_min,rt_max,mz_tolerance,mz_rt_uid,rt_alignment_applied,manual_curation_applied,label
0,atl-ref-ema-hilicz-pos-9fc8b14f2ecb4f4086b0ff36b93ce062,Default HILICZ EMA Atlas Positive,Default experimental compounds used for targeted analysis,HILICZ,POS,EMA,REFERENCE,cmp-d7b56c060fd7491ebf68c3362e1d03f4,NOSCAPINE HYDROCHLORIDE,AKNNEGZIBPJZJG-QZTJIDSGSA-N,...,[M+H]+,414.154724,0.806009,0.306009,1.306009,5.0,mzrt-ref-98eba4dd7b1c4b4a950a387614cdbed4,False,False,NOSCAPINE HYDROCHLORIDE
1,atl-ref-ema-hilicz-pos-9fc8b14f2ecb4f4086b0ff36b93ce062,Default HILICZ EMA Atlas Positive,Default experimental compounds used for targeted analysis,HILICZ,POS,EMA,REFERENCE,cmp-37dbcc5781774d0ab33cfe807552c38f,PYRAZINAMIDE,IPEHBUMCGVEMRF-UHFFFAOYSA-N,...,[M+H]+,124.050537,0.807897,0.307897,1.307897,5.0,mzrt-ref-916e4488fd0a4d56a14822f9e8e299b9,False,False,PYRAZINAMIDE
2,atl-ref-ema-hilicz-pos-9fc8b14f2ecb4f4086b0ff36b93ce062,Default HILICZ EMA Atlas Positive,Default experimental compounds used for targeted analysis,HILICZ,POS,EMA,REFERENCE,cmp-e07a2608e1f34c9b913185e095fd74ce,CLOTRIMAZOLE,VNFPBHJOKIVQEB-UHFFFAOYSA-N,...,[M+H]+,345.115295,0.810178,0.310178,1.310178,5.0,mzrt-ref-a757c3c42a0f489ca9dde4e6e0948c31,False,False,CLOTRIMAZOLE
3,atl-ref-ema-hilicz-pos-9fc8b14f2ecb4f4086b0ff36b93ce062,Default HILICZ EMA Atlas Positive,Default experimental compounds used for targeted analysis,HILICZ,POS,EMA,REFERENCE,cmp-008835a935b740e8b874797b092298bf,Acetolactate,WTLNOANVTIKPEE-UHFFFAOYSA-N,...,[M-H2O+H]+,115.038971,0.810971,0.310971,1.310971,5.0,mzrt-ref-e6b6936ff2d2461fb6cd8a42a25424f6,False,False,Acetolactate
4,atl-ref-ema-hilicz-pos-9fc8b14f2ecb4f4086b0ff36b93ce062,Default HILICZ EMA Atlas Positive,Default experimental compounds used for targeted analysis,HILICZ,POS,EMA,REFERENCE,cmp-477fece4a9eb476590ea4b700a3c36f1,SULFAMETHOXAZOLE,JLKIGFTWXXRPMT-UHFFFAOYSA-N,...,[M+H]+,254.059387,0.811501,0.311501,1.311501,5.0,mzrt-ref-57fbad6ccdaf4a0fa1b632c7c1cfbbd0,False,False,SULFAMETHOXAZOLE

2026-02-23 13:16:22 | metatlas2.workflow_objects | INFO | Validating atlas Default HILICZ EMA Atlas Positive (UID: atl-ref-ema-hilicz-pos-9fc8b14f2ecb4f4086b0ff36b93ce062) with 573 compounds...
2026-02-23 13:16:22 | metatlas2.workflow_objects | INFO | Atlas passed validation!
2026-02-23 13:16:22 | metatlas2.workflow_objects | INFO | Validating atlas Default HILICZ EMA Atlas Positive (RT aligned) (UID: atl-rta-ema-hilicz-pos-b257abac519e40e3a9c9ee696aa89624) with 573 compounds...
2026-02-23 13:16:22 | metatlas2.workflow_objects | INFO | Atlas passed validation!
2026-02-23 13:16:22 | metatlas2.rt_align_tools | INFO | Applied RT alignment model to 3 target atlases. RT shift stats: {'rt_shift_min': -0.4252880791121978, 'rt_shift_max': 0.16460620235074575, 'rt_shift_median': -0.27507944538112383}
2026-02-23 13:16:22 | metatlas2.database_interact | INFO | Saving atlas Default HILICZ QC Atlas Positive (RT aligned) to database at /Users/BKieft/Metabolomics/metatlas_lite_data/projects/20260106_JGI_LP-AC_510770_StrigoArab_final_EXP120B_HILICZ_USHXG03402/20260106_JGI_LP-AC_510770_StrigoArab_final_EXP120B_HILICZ_USHXG03402.duckdb...
2026-02-23 13:16:22 | metatlas2.database_interact | INFO | All compounds verified to exist in the database.
2026-02-23 13:16:22 | metatlas2.database_interact | INFO | Saved atlas Default HILICZ QC Atlas Positive (RT aligned) to database with UID atl-rta-qc-hilicz-pos-1b28bd8beb0a4d239d29508f2e5a06d5, chromatography HILICZ, polarity POS, and analysis type QC
2026-02-23 13:16:22 | metatlas2.database_interact | INFO |   References created: 20
2026-02-23 13:16:22 | metatlas2.database_interact | INFO |   References reused: 0
2026-02-23 13:16:22 | metatlas2.database_interact | INFO |   Total associations: 20
2026-02-23 13:16:22 | metatlas2.database_interact | INFO | Saving atlas Default HILICZ ISTD Atlas Positive (RT aligned) to database at /Users/BKieft/Metabolomics/metatlas_lite_data/projects/20260106_JGI_LP-AC_510770_StrigoArab_final_EXP120B_HILICZ_USHXG03402/20260106_JGI_LP-AC_510770_StrigoArab_final_EXP120B_HILICZ_USHXG03402.duckdb...
2026-02-23 13:16:22 | metatlas2.database_interact | INFO | All compounds verified to exist in the database.
2026-02-23 13:16:22 | metatlas2.database_interact | INFO | Saved atlas Default HILICZ ISTD Atlas Positive (RT aligned) to database with UID atl-rta-istd-hilicz-pos-467e971e8ae14e7e93d55508cf5ef181, chromatography HILICZ, polarity POS, and analysis type ISTD
2026-02-23 13:16:22 | metatlas2.database_interact | INFO |   References created: 65
2026-02-23 13:16:22 | metatlas2.database_interact | INFO |   References reused: 0
2026-02-23 13:16:22 | metatlas2.database_interact | INFO |   Total associations: 65
2026-02-23 13:16:22 | metatlas2.database_interact | INFO | Saving atlas Default HILICZ EMA Atlas Positive (RT aligned) to database at /Users/BKieft/Metabolomics/metatlas_lite_data/projects/20260106_JGI_LP-AC_510770_StrigoArab_final_EXP120B_HILICZ_USHXG03402/20260106_JGI_LP-AC_510770_StrigoArab_final_EXP120B_HILICZ_USHXG03402.duckdb...
2026-02-23 13:16:22 | metatlas2.database_interact | INFO | All compounds verified to exist in the database.
2026-02-23 13:16:23 | metatlas2.database_interact | INFO | Saved atlas Default HILICZ EMA Atlas Positive (RT aligned) to database with UID atl-rta-ema-hilicz-pos-b257abac519e40e3a9c9ee696aa89624, chromatography HILICZ, polarity POS, and analysis type EMA
2026-02-23 13:16:23 | metatlas2.database_interact | INFO |   References created: 573
2026-02-23 13:16:23 | metatlas2.database_interact | INFO |   References reused: 0
2026-02-23 13:16:23 | metatlas2.database_interact | INFO |   Total associations: 573
2026-02-23 13:16:23 | metatlas2.rt_align_tools | INFO | Generating RT alignment model summary...
2026-02-23 13:16:23 | metatlas2.rt_align_tools | INFO | RT Alignment Model Summary:
2026-02-23 13:16:23 | metatlas2.rt_align_tools | INFO |   Polynomial degree: 2
2026-02-23 13:16:23 | metatlas2.rt_align_tools | INFO |   R²: 0.9968
2026-02-23 13:16:23 | metatlas2.rt_align_tools | INFO |   RMSE: 0.3007 min
2026-02-23 13:16:23 | metatlas2.rt_align_tools | INFO |   Equation: RT_aligned = 0.256158 + 0.882318 * RT_atlas + 0.005081 * RT_atlas^2
2026-02-23 13:16:23 | metatlas2.rt_align_tools | INFO |   Compounds used for modeling: 0
2026-02-23 13:16:23 | metatlas2.rt_align_tools | INFO | RT Shift Statistics (across all aligned compounds):
2026-02-23 13:16:23 | metatlas2.rt_align_tools | INFO |   Min RT shift: -0.4253 min
2026-02-23 13:16:23 | metatlas2.rt_align_tools | INFO |   Max RT shift: 0.1646 min
2026-02-23 13:16:23 | metatlas2.rt_align_tools | INFO |   Median RT shift: -0.2751 min
2026-02-23 13:16:23 | metatlas2.workflow_objects | INFO | RT alignment procedure complete for RT alignment number 0 and chromatography HILICZ!