In [1]:
import sys
import pandas as pd
pd.options.display.max_colwidth = 600

sys.path.append('/global/homes/b/bkieft/metatlas2/metatlas2')
import logging_config as lcf
import logging
import workflow_objects as wfo
import load_tools as ldt

In [2]:
# Set up logging with level
log_level = logging.INFO
lcf.setup_logging(log_level=log_level)
logger = lcf.get_logger('rt_alignment', log_level=log_level)

In [3]:
# Load configuration file
ANALYSIS_CONFIG = ldt.load_metatlas2_config("/global/homes/b/bkieft/metatlas2/configs/analysis.yaml")

2026-02-26 15:27:06 | metatlas2.load_tools | INFO | Loaded metatlas2 configuration from /global/homes/b/bkieft/metatlas2/configs/analysis.yaml

In [4]:
# Set up analysis parameters
PROJECT_NAME = "20260106_JGI_LP-AC_510770_StrigoArab_final_EXP120B_HILICZ_USHXG03402"
RT_ALIGN_CHROM = "HILICZ"
RT_ALIGN_NUM = 0

In [5]:
# RT Alignment
wfo.run_rt_alignment(
    config=ANALYSIS_CONFIG,
    project_name=PROJECT_NAME,
    rt_alignment_number=RT_ALIGN_NUM,
    chromatography=RT_ALIGN_CHROM
)

2026-02-26 15:27:06 | metatlas2.workflow_objects | INFO | Setting up RTAlign object for HILICZ chromatography and RT alignment number 0...
2026-02-26 15:27:06 | metatlas2.workflow_objects | INFO | Setting up workflow paths...
2026-02-26 15:27:06 | metatlas2.workflow_objects | INFO | Checking for existing RT model in database with UID atl-ref-qc-hilicz-pos-eeadc38364104e1e98c30f5ae0051d8d (HILICZ) and RT Alignment number 0
2026-02-26 15:27:06 | metatlas2.workflow_objects | WARNING | Variable 'use_existing_rt_alignment' is True, but no existing RT alignment model found in database for atlas atl-ref-qc-hilicz-pos-eeadc38364104e1e98c30f5ae0051d8d. Creating new RT Alignment model.
2026-02-26 15:27:06 | metatlas2.workflow_objects | INFO | Retrieving all LCMS runs for project...
2026-02-26 15:27:06 | metatlas2.database_interact | INFO | Retrieved 34 LC/MS run files from database with filters: file_types=None, chromatography=None, polarity=None, format=parquet
2026-02-26 15:27:06 | metatlas2.workflow_objects | INFO | Filtering 34 LCMS runs...
2026-02-26 15:27:06 | metatlas2.lcmsruns_tools | INFO | Filtering 34 LCMS runs with parameters: file_type=['qc'], file_format=parquet, chromatography=HILIC, polarity=None...
2026-02-26 15:27:06 | metatlas2.lcmsruns_tools | INFO | Filtered to 4 out of 34 total files.
2026-02-26 15:27:06 | metatlas2.workflow_objects | INFO | Loading atlas with UID atl-ref-qc-hilicz-pos-eeadc38364104e1e98c30f5ae0051d8d from database...
2026-02-26 15:27:06 | metatlas2.database_interact | INFO | Retrieved 20 compounds for atlas atl-ref-qc-hilicz-pos-eeadc38364104e1e98c30f5ae0051d8d (Default HILICZ QC Atlas Positive)

,atlas_uid,atlas_name,atlas_description,chromatography,polarity,analysis_type,atlas_type,compound_uid,compound_name,inchi_key,inchi,adduct,mz,rt_peak,rt_min,rt_max,mz_tolerance,mz_rt_uid,rt_alignment_applied,manual_curation_applied
0,atl-ref-qc-hilicz-pos-eeadc38364104e1e98c30f5ae0051d8d,Default HILICZ QC Atlas Positive,Default QC compounds used for RT alignment,HILICZ,POS,QC,REFERENCE,cmp-11a0187b0f52452d9b60b60e9495e950,ABMBA (unlabeled),LCMZECCEEOQWLQ-UHFFFAOYSA-N,"InChI=1S/C8H8BrNO2/c1-4-2-5(8(11)12)7(10)6(9)3-4/h2-3H,10H2,1H3,(H,11,12)",[M+H]+,229.981094,1.093806,0.793806,1.393806,5.0,mzrt-ref-f35897d5cf854d898250415fae8e60be,False,False
1,atl-ref-qc-hilicz-pos-eeadc38364104e1e98c30f5ae0051d8d,Default HILICZ QC Atlas Positive,Default QC compounds used for RT alignment,HILICZ,POS,QC,REFERENCE,cmp-5a591e980afe4edc8abe9776797ec1c4,"thymine (U - 13C, 15N)",RWQNBRDOKXIBIV-BNUYUSEDSA-N,"InChI=1S/C5H6N2O2/c1-3-2-6-5(9)7-4(3)8/h2H,1H3,(H2,6,7,8,9)/i1+1,2+1,3+1,4+1,5+1,6+1,7+1",[M+H]+,134.061035,1.255231,0.955231,1.555231,5.0,mzrt-ref-cc3142e7cb034f8ea6103645c184b2fd,False,False
2,atl-ref-qc-hilicz-pos-eeadc38364104e1e98c30f5ae0051d8d,Default HILICZ QC Atlas Positive,Default QC compounds used for RT alignment,HILICZ,POS,QC,REFERENCE,cmp-30ede4101dc14c95b240ceb40474de43,adenine (U - 15N),GFFGJBXGBJISGV-CIKZIQIKSA-N,"InChI=1S/C5H5N5/c6-4-3-5(9-1-7-3)10-2-8-4/h1-2H,(H3,6,7,8,9,10)/i6+1,7+1,8+1,9+1,10+1",[M+H]+,141.046936,2.677602,2.377602,2.977602,5.0,mzrt-ref-08090589aa744d90a1e636b9653d312d,False,False
3,atl-ref-qc-hilicz-pos-eeadc38364104e1e98c30f5ae0051d8d,Default HILICZ QC Atlas Positive,Default QC compounds used for RT alignment,HILICZ,POS,QC,REFERENCE,cmp-6ef4be81c781466d862310fef5ead158,hypoxanthine (U - 15N),FDGQSTZJBFJUBT-NNZQUYKOSA-N,"InChI=1S/C5H4N4O/c10-5-3-4(7-1-6-3)8-2-9-5/h1-2H,(H2,6,7,8,9,10)/i6+1,7+1,8+1,9+1",[M+H]+,141.033920,3.102967,2.802967,3.402967,5.0,mzrt-ref-9b8237fc001e4aedb9800a718e70d30a,False,False
4,atl-ref-qc-hilicz-pos-eeadc38364104e1e98c30f5ae0051d8d,Default HILICZ QC Atlas Positive,Default QC compounds used for RT alignment,HILICZ,POS,QC,REFERENCE,cmp-df061de1efea4861a36a388830f59d49,inosine (U - 15N),UGQMRVRMYYASKQ-SHKQESLVSA-N,"InChI=1S/C10H12N4O5/c15-1-4-6(16)7(17)10(19-4)14-3-13-5-8(14)11-2-12-9(5)18/h2-4,6-7,10,15-17H,1H2,(H,11,12,18)/t4-,6-,7-,10-/m1/s1/i11+1,12+1,13+1,14+1",[M+H]+,273.076172,5.434236,5.134236,5.734236,5.0,mzrt-ref-33902ff439f541b29dcc18300a51b1da,False,False

2026-02-26 15:27:06 | metatlas2.workflow_objects | INFO | Validating atlas Default HILICZ QC Atlas Positive (UID: atl-ref-qc-hilicz-pos-eeadc38364104e1e98c30f5ae0051d8d) with 20 compounds...
2026-02-26 15:27:06 | metatlas2.workflow_objects | INFO | Atlas passed validation!
2026-02-26 15:27:06 | metatlas2.workflow_objects | INFO | Passing Atlas and LCMSRuns to data extractor...
2026-02-26 15:27:06 | metatlas2.extract_data_from_parquet | INFO | Starting data extraction based on atl-ref-qc-hilicz-pos-eeadc38364104e1e98c30f5ae0051d8d (Default HILICZ QC Atlas Positive) for stage 'rt_alignment' from 4 LCMS runs...
2026-02-26 15:27:06 | metatlas2.extract_data_from_parquet | INFO | Initiating an experimental data object to hold results during analysis...
2026-02-26 15:27:06 | metatlas2.extract_data_from_parquet | INFO | Starting data extraction for 20 compounds from 4 project files...
2026-02-26 15:27:06 | metatlas2.extract_data_from_parquet | INFO | Using ppm_tolerance=20.0 and extra_time=1.0 for data extraction.
2026-02-26 15:27:06 | metatlas2.extract_data_from_parquet | INFO | Using parallel processing with 4 workers...

Extracting data from parquet files:   0%|          | 0/4 [00:00<?, ?it/s]

2026-02-26 15:27:07 | metatlas2.workflow_objects | INFO | Passing ExperimentalData and Atlas to summarizer...
2026-02-26 15:27:07 | metatlas2.rt_align_tools | INFO | Evaluating QC compound matching statistics from ExperimentalData...
2026-02-26 15:27:07 | metatlas2.rt_align_tools | INFO | QC Compound Matching Summary:
2026-02-26 15:27:07 | metatlas2.rt_align_tools | INFO |   Total compounds: 20
2026-02-26 15:27:07 | metatlas2.rt_align_tools | INFO |   Compounds with matches: 20 (100.0%)
2026-02-26 15:27:07 | metatlas2.rt_align_tools | INFO |   Compounds without matches: 0
2026-02-26 15:27:07 | metatlas2.rt_align_tools | INFO |   Total files analyzed: 4
2026-02-26 15:27:07 | metatlas2.rt_align_tools | INFO |   Files with matches: 4
2026-02-26 15:27:07 | metatlas2.rt_align_tools | INFO |   Total peaks extracted: 50
2026-02-26 15:27:07 | metatlas2.rt_align_tools | INFO |   Average peaks per matched compound: 2.5
2026-02-26 15:27:07 | metatlas2.rt_align_tools | INFO |   Average compounds matched per file: 12.5
2026-02-26 15:27:07 | metatlas2.workflow_objects | INFO | Passing ExperimentalData, Atlas, and RTAlign to RT alignment model builder...
2026-02-26 15:27:07 | metatlas2.rt_align_tools | INFO | Building RT alignment model from experimental data and atlas...
2026-02-26 15:27:07 | metatlas2.rt_align_tools | INFO | RT Statistics Summary:
2026-02-26 15:27:07 | metatlas2.rt_align_tools | INFO |   Atlas RT range: 1.09 - 17.01 min
2026-02-26 15:27:07 | metatlas2.rt_align_tools | INFO |   Observed RT range (median): 1.29 - 17.09 min
2026-02-26 15:27:07 | metatlas2.rt_align_tools | INFO |   Mean RT difference (observed - atlas): -0.207 ± 0.249 min
2026-02-26 15:27:07 | metatlas2.rt_align_tools | INFO | Using 19 compounds with ≥1 observations (QC files) for modeling
2026-02-26 15:27:07 | metatlas2.rt_align_tools | INFO | Building polynomial model (degree 2)...
2026-02-26 15:27:07 | metatlas2.rt_align_tools | INFO | Model built successfully:
2026-02-26 15:27:07 | metatlas2.rt_align_tools | INFO |   Model type: Polynomial degree 2
2026-02-26 15:27:07 | metatlas2.rt_align_tools | INFO |   R² = 0.9993
2026-02-26 15:27:07 | metatlas2.rt_align_tools | INFO |   RMSE = 0.1380 min
2026-02-26 15:27:07 | metatlas2.rt_align_tools | INFO |   Max residual = 0.3278 min
2026-02-26 15:27:07 | metatlas2.rt_align_tools | INFO |   Equation: RT_aligned = 0.302214 + 0.840423 * RT_atlas + 0.008377 * RT_atlas^2
2026-02-26 15:27:07 | metatlas2.rt_align_tools | INFO | Compound RT Statistics:

,compound_name,inchi_key,atlas_rt_peak,exp_rt_median,rt_diff_median,observation_count,exp_rt_std
0,ABMBA (unlabeled),LCMZECCEEOQWLQ-UHFFFAOYSA-N,1.093806,1.287296,0.193489,4,0.027533
1,"thymine (U - 13C, 15N)",RWQNBRDOKXIBIV-BNUYUSEDSA-N,1.255231,1.319569,0.064338,2,0.016115
2,adenine (U - 15N),GFFGJBXGBJISGV-CIKZIQIKSA-N,2.677602,2.553301,-0.124301,2,0.017951
3,hypoxanthine (U - 15N),FDGQSTZJBFJUBT-NNZQUYKOSA-N,3.102967,3.052305,-0.050662,2,0.004190
4,inosine (U - 15N),UGQMRVRMYYASKQ-SHKQESLVSA-N,5.434236,5.136427,-0.297809,2,0.028265
5,guanine (U - 15N),UYTPUPDQBNUYGX-CIKZIQIKSA-N,6.265360,5.729845,-0.535515,4,0.433614
6,"phenylalanine (U - 13C, 15N)",COLNVLDHVKWLRT-CMLFETTRSA-N,8.979305,8.823132,-0.156173,2,0.016559
7,"tryptophan (U - 13C, 15N)",QIVBCDIJIAJPQS-HNEHNLBWSA-N,10.156650,10.001759,-0.154891,2,0.002917
8,"methionine (U - 13C, 15N)",FFEARJCKVFRZRR-XAFSXMPTSA-N,10.440955,9.662514,-0.778441,4,0.389513
9,"valine (U - 13C, 15N)",KZSNJWFQEVHDMF-XAFSXMPTSA-N,11.116009,10.568719,-0.547290,3,0.293765
10,"tyrosine (U - 13C, 15N)",OUYCCCASQSFEME-CMLFETTRSA-N,11.855156,11.493771,-0.361385,2,0.007042
11,"alanine (U - 13C, 15N)",QNAYBMKLOCPYGJ-UVYXLFMMSA-N,13.405090,13.018167,-0.386924,2,0.012983
12,"threonine (U - 13C, 15N)",AYFVYJQAPQTCCC-KJQIOZMZSA-N,13.489573,13.110671,-0.378902,2,0.004192
13,"asparagine (U - 13C, 15N)",DCXYFEDJOCDNAF-FLEDYEEXSA-N,14.368089,14.121313,-0.246776,2,0.006375
14,"glutamic acid (U - 13C, 15N)",WHUUTDBJXJRKMK-UFLWJPECSA-N,15.935390,15.774802,-0.160587,3,0.310745
15,"aspartic acid (U - 13C, 15N)",CKLJMWTZIZZHCS-NYTNKSBQSA-N,16.130360,15.985654,-0.144705,2,0.007095
16,"cystine (U - 13C, 15N)",LEVWYRKDKASIDU-OGYFDXEDSA-N,16.904308,16.898122,-0.006186,4,0.446041
17,"arginine (U - 13C, 15N)",ODKSFYDXXFIFQN-GZYYCROJSA-N,16.939915,17.005967,0.066052,2,0.001500
18,"lysine (U - 13C, 15N)",KDXKERNSBIXSRK-JMKXWGMHSA-N,17.011311,17.087776,0.076466,2,0.004295

2026-02-26 15:27:07 | metatlas2.workflow_objects | INFO | Passing RTAlign object to model database table saver...
2026-02-26 15:27:07 | metatlas2.database_interact | INFO | Saving RT alignment model to project database...
2026-02-26 15:27:07 | metatlas2.database_interact | INFO | RT alignment model saved to database with UID: rta-deea341cf9314631997448ae830d6464
2026-02-26 15:27:07 | metatlas2.workflow_objects | INFO | Passing RTAlign object to model visualizer...
2026-02-26 15:27:07 | metatlas2.rt_align_tools | INFO | Plotting RT alignment model results to figure...
2026-02-26 15:27:10 | metatlas2.rt_align_tools | INFO | Plot saved to /pscratch/sd/b/bkieft/metatlas_lite_data/projects/20260106_JGI_LP-AC_510770_StrigoArab_final_EXP120B_HILICZ_USHXG03402/20260106_JGI_LP-AC_510770_StrigoArab_final_EXP120B_HILICZ_USHXG03402_RTA0/rt_alignment_results/summary-for-rta-deea341cf9314631997448ae830d6464.pdf
2026-02-26 15:27:10 | metatlas2.rt_align_tools | INFO | RT alignment model plot saved to /pscratch/sd/b/bkieft/metatlas_lite_data/projects/20260106_JGI_LP-AC_510770_StrigoArab_final_EXP120B_HILICZ_USHXG03402/20260106_JGI_LP-AC_510770_StrigoArab_final_EXP120B_HILICZ_USHXG03402_RTA0/rt_alignment_results/summary-for-rta-deea341cf9314631997448ae830d6464.pdf
2026-02-26 15:27:10 | metatlas2.workflow_objects | INFO | Passing RTAlign object to alignment applicator...
2026-02-26 15:27:10 | metatlas2.rt_align_tools | INFO | Applying RT alignment model to target atlases and generating RT-aligned Atlas objects...
2026-02-26 15:27:10 | metatlas2.rt_align_tools | INFO | Loading HILICZ POS QC target atlas with UID atl-ref-qc-hilicz-pos-eeadc38364104e1e98c30f5ae0051d8d for applying RT alignment model...
2026-02-26 15:27:10 | metatlas2.workflow_objects | INFO | Loading atlas with UID atl-ref-qc-hilicz-pos-eeadc38364104e1e98c30f5ae0051d8d from database...
2026-02-26 15:27:10 | metatlas2.database_interact | INFO | Retrieved 20 compounds for atlas atl-ref-qc-hilicz-pos-eeadc38364104e1e98c30f5ae0051d8d (Default HILICZ QC Atlas Positive)

,atlas_uid,atlas_name,atlas_description,chromatography,polarity,analysis_type,atlas_type,compound_uid,compound_name,inchi_key,inchi,adduct,mz,rt_peak,rt_min,rt_max,mz_tolerance,mz_rt_uid,rt_alignment_applied,manual_curation_applied
0,atl-ref-qc-hilicz-pos-eeadc38364104e1e98c30f5ae0051d8d,Default HILICZ QC Atlas Positive,Default QC compounds used for RT alignment,HILICZ,POS,QC,REFERENCE,cmp-11a0187b0f52452d9b60b60e9495e950,ABMBA (unlabeled),LCMZECCEEOQWLQ-UHFFFAOYSA-N,"InChI=1S/C8H8BrNO2/c1-4-2-5(8(11)12)7(10)6(9)3-4/h2-3H,10H2,1H3,(H,11,12)",[M+H]+,229.981094,1.093806,0.793806,1.393806,5.0,mzrt-ref-f35897d5cf854d898250415fae8e60be,False,False
1,atl-ref-qc-hilicz-pos-eeadc38364104e1e98c30f5ae0051d8d,Default HILICZ QC Atlas Positive,Default QC compounds used for RT alignment,HILICZ,POS,QC,REFERENCE,cmp-5a591e980afe4edc8abe9776797ec1c4,"thymine (U - 13C, 15N)",RWQNBRDOKXIBIV-BNUYUSEDSA-N,"InChI=1S/C5H6N2O2/c1-3-2-6-5(9)7-4(3)8/h2H,1H3,(H2,6,7,8,9)/i1+1,2+1,3+1,4+1,5+1,6+1,7+1",[M+H]+,134.061035,1.255231,0.955231,1.555231,5.0,mzrt-ref-cc3142e7cb034f8ea6103645c184b2fd,False,False
2,atl-ref-qc-hilicz-pos-eeadc38364104e1e98c30f5ae0051d8d,Default HILICZ QC Atlas Positive,Default QC compounds used for RT alignment,HILICZ,POS,QC,REFERENCE,cmp-30ede4101dc14c95b240ceb40474de43,adenine (U - 15N),GFFGJBXGBJISGV-CIKZIQIKSA-N,"InChI=1S/C5H5N5/c6-4-3-5(9-1-7-3)10-2-8-4/h1-2H,(H3,6,7,8,9,10)/i6+1,7+1,8+1,9+1,10+1",[M+H]+,141.046936,2.677602,2.377602,2.977602,5.0,mzrt-ref-08090589aa744d90a1e636b9653d312d,False,False
3,atl-ref-qc-hilicz-pos-eeadc38364104e1e98c30f5ae0051d8d,Default HILICZ QC Atlas Positive,Default QC compounds used for RT alignment,HILICZ,POS,QC,REFERENCE,cmp-6ef4be81c781466d862310fef5ead158,hypoxanthine (U - 15N),FDGQSTZJBFJUBT-NNZQUYKOSA-N,"InChI=1S/C5H4N4O/c10-5-3-4(7-1-6-3)8-2-9-5/h1-2H,(H2,6,7,8,9,10)/i6+1,7+1,8+1,9+1",[M+H]+,141.033920,3.102967,2.802967,3.402967,5.0,mzrt-ref-9b8237fc001e4aedb9800a718e70d30a,False,False
4,atl-ref-qc-hilicz-pos-eeadc38364104e1e98c30f5ae0051d8d,Default HILICZ QC Atlas Positive,Default QC compounds used for RT alignment,HILICZ,POS,QC,REFERENCE,cmp-df061de1efea4861a36a388830f59d49,inosine (U - 15N),UGQMRVRMYYASKQ-SHKQESLVSA-N,"InChI=1S/C10H12N4O5/c15-1-4-6(16)7(17)10(19-4)14-3-13-5-8(14)11-2-12-9(5)18/h2-4,6-7,10,15-17H,1H2,(H,11,12,18)/t4-,6-,7-,10-/m1/s1/i11+1,12+1,13+1,14+1",[M+H]+,273.076172,5.434236,5.134236,5.734236,5.0,mzrt-ref-33902ff439f541b29dcc18300a51b1da,False,False

2026-02-26 15:27:10 | metatlas2.workflow_objects | INFO | Validating atlas Default HILICZ QC Atlas Positive (UID: atl-ref-qc-hilicz-pos-eeadc38364104e1e98c30f5ae0051d8d) with 20 compounds...
2026-02-26 15:27:10 | metatlas2.workflow_objects | INFO | Atlas passed validation!
2026-02-26 15:27:10 | metatlas2.workflow_objects | INFO | Validating atlas Default HILICZ QC Atlas Positive (RT aligned) (UID: atl-rta-qc-hilicz-pos-5c88c316a5974d6793365b8a4bd1b39e) with 20 compounds...
2026-02-26 15:27:10 | metatlas2.workflow_objects | INFO | Atlas passed validation!
2026-02-26 15:27:10 | metatlas2.rt_align_tools | INFO | Loading HILICZ POS ISTD target atlas with UID atl-ref-istd-hilicz-pos-57e133f3430043ebb3290774bbafdb21 for applying RT alignment model...
2026-02-26 15:27:10 | metatlas2.workflow_objects | INFO | Loading atlas with UID atl-ref-istd-hilicz-pos-57e133f3430043ebb3290774bbafdb21 from database...
2026-02-26 15:27:10 | metatlas2.database_interact | INFO | Retrieved 65 compounds for atlas atl-ref-istd-hilicz-pos-57e133f3430043ebb3290774bbafdb21 (Default HILICZ ISTD Atlas Positive)

,atlas_uid,atlas_name,atlas_description,chromatography,polarity,analysis_type,atlas_type,compound_uid,compound_name,inchi_key,inchi,adduct,mz,rt_peak,rt_min,rt_max,mz_tolerance,mz_rt_uid,rt_alignment_applied,manual_curation_applied
0,atl-ref-istd-hilicz-pos-57e133f3430043ebb3290774bbafdb21,Default HILICZ ISTD Atlas Positive,Default internal standard compounds used for checking performance,HILICZ,POS,ISTD,REFERENCE,cmp-11a0187b0f52452d9b60b60e9495e950,ABMBA (unlabeled),LCMZECCEEOQWLQ-UHFFFAOYSA-N,"InChI=1S/C8H8BrNO2/c1-4-2-5(8(11)12)7(10)6(9)3-4/h2-3H,10H2,1H3,(H,11,12)",[M+H]+,229.981094,1.093806,0.793806,1.393806,5.0,mzrt-ref-f35897d5cf854d898250415fae8e60be,False,False
1,atl-ref-istd-hilicz-pos-57e133f3430043ebb3290774bbafdb21,Default HILICZ ISTD Atlas Positive,Default internal standard compounds used for checking performance,HILICZ,POS,ISTD,REFERENCE,cmp-6f1914c6411c458f912e677857e2c603,nicotinamide (U - 13C),DFPAKSUCGFBDDF-IDEBNGHGSA-N,"InChI=1S/C6H6N2O/c7-6(9)5-2-1-3-8-4-5/h1-4H,(H2,7,9)/i1+1,2+1,3+1,4+1,5+1,6+1",[M+H]+,129.075424,1.146589,0.846589,1.446589,5.0,mzrt-ref-14c9b2c018e247359c9bd82d975f318a,False,False
2,atl-ref-istd-hilicz-pos-57e133f3430043ebb3290774bbafdb21,Default HILICZ ISTD Atlas Positive,Default internal standard compounds used for checking performance,HILICZ,POS,ISTD,REFERENCE,cmp-8f26a0c30cb44ac0a09de8cf88c01388,nicotinamide (unlabeled),DFPAKSUCGFBDDF-UHFFFAOYSA-N,"InChI=1S/C6H6N2O/c7-6(9)5-2-1-3-8-4-5/h1-4H,(H2,7,9)",[M+H]+,123.055290,1.146589,0.846589,1.446589,5.0,mzrt-ref-817521fd4bb946249adf0d5acfc5dc19,False,False
3,atl-ref-istd-hilicz-pos-57e133f3430043ebb3290774bbafdb21,Default HILICZ ISTD Atlas Positive,Default internal standard compounds used for checking performance,HILICZ,POS,ISTD,REFERENCE,cmp-5a591e980afe4edc8abe9776797ec1c4,"thymine (U - 13C, 15N)",RWQNBRDOKXIBIV-BNUYUSEDSA-N,"InChI=1S/C5H6N2O2/c1-3-2-6-5(9)7-4(3)8/h2H,1H3,(H2,6,7,8,9)/i1+1,2+1,3+1,4+1,5+1,6+1,7+1",[M+H]+,134.061035,1.255231,0.955231,1.555231,5.0,mzrt-ref-cc3142e7cb034f8ea6103645c184b2fd,False,False
4,atl-ref-istd-hilicz-pos-57e133f3430043ebb3290774bbafdb21,Default HILICZ ISTD Atlas Positive,Default internal standard compounds used for checking performance,HILICZ,POS,ISTD,REFERENCE,cmp-fcb50631a9a74d9fba4c17a905754644,thymine (unlabeled),RWQNBRDOKXIBIV-UHFFFAOYSA-N,"InChI=1S/C5H6N2O2/c1-3-2-6-5(9)7-4(3)8/h2H,1H3,(H2,6,7,8,9)",[M+H]+,127.050201,1.255231,0.955231,1.555231,5.0,mzrt-ref-312fdd4c23924524863bd76759c54341,False,False

2026-02-26 15:27:10 | metatlas2.workflow_objects | INFO | Validating atlas Default HILICZ ISTD Atlas Positive (UID: atl-ref-istd-hilicz-pos-57e133f3430043ebb3290774bbafdb21) with 65 compounds...
2026-02-26 15:27:10 | metatlas2.workflow_objects | INFO | Atlas passed validation!
2026-02-26 15:27:10 | metatlas2.workflow_objects | INFO | Validating atlas Default HILICZ ISTD Atlas Positive (RT aligned) (UID: atl-rta-istd-hilicz-pos-2629de26a08b4af8b3cac8fadf695919) with 65 compounds...
2026-02-26 15:27:10 | metatlas2.workflow_objects | INFO | Atlas passed validation!
2026-02-26 15:27:10 | metatlas2.rt_align_tools | INFO | Applied RT alignment model to 2 target atlases. RT shift stats: {'rt_shift_min': -0.4576997195913659, 'rt_shift_max': 0.13769122588871197, 'rt_shift_median': -0.27339142671543293}
2026-02-26 15:27:10 | metatlas2.workflow_objects | INFO | Passing aligned Atlases to database saver...
2026-02-26 15:27:10 | metatlas2.database_interact | INFO | Saving atlas Default HILICZ QC Atlas Positive (RT aligned) to database at /pscratch/sd/b/bkieft/metatlas_lite_data/projects/20260106_JGI_LP-AC_510770_StrigoArab_final_EXP120B_HILICZ_USHXG03402/20260106_JGI_LP-AC_510770_StrigoArab_final_EXP120B_HILICZ_USHXG03402.duckdb...
2026-02-26 15:27:10 | metatlas2.database_interact | INFO | All compounds verified to exist in the main database.
2026-02-26 15:27:10 | metatlas2.database_interact | INFO | Saved atlas Default HILICZ QC Atlas Positive (RT aligned) to database with UID atl-rta-qc-hilicz-pos-5c88c316a5974d6793365b8a4bd1b39e, chromatography HILICZ, polarity POS, and analysis type QC
2026-02-26 15:27:10 | metatlas2.database_interact | INFO |   References created: 20
2026-02-26 15:27:10 | metatlas2.database_interact | INFO |   References reused: 0
2026-02-26 15:27:10 | metatlas2.database_interact | INFO |   Total associations: 20
2026-02-26 15:27:10 | metatlas2.database_interact | INFO | Saving atlas Default HILICZ ISTD Atlas Positive (RT aligned) to database at /pscratch/sd/b/bkieft/metatlas_lite_data/projects/20260106_JGI_LP-AC_510770_StrigoArab_final_EXP120B_HILICZ_USHXG03402/20260106_JGI_LP-AC_510770_StrigoArab_final_EXP120B_HILICZ_USHXG03402.duckdb...
2026-02-26 15:27:10 | metatlas2.database_interact | INFO | All compounds verified to exist in the main database.
2026-02-26 15:27:11 | metatlas2.database_interact | INFO | Saved atlas Default HILICZ ISTD Atlas Positive (RT aligned) to database with UID atl-rta-istd-hilicz-pos-2629de26a08b4af8b3cac8fadf695919, chromatography HILICZ, polarity POS, and analysis type ISTD
2026-02-26 15:27:11 | metatlas2.database_interact | INFO |   References created: 65
2026-02-26 15:27:11 | metatlas2.database_interact | INFO |   References reused: 0
2026-02-26 15:27:11 | metatlas2.database_interact | INFO |   Total associations: 65
2026-02-26 15:27:11 | metatlas2.workflow_objects | INFO | Passing RTAlign object to RT alignment summary generator...
2026-02-26 15:27:11 | metatlas2.rt_align_tools | INFO | Generating RT alignment model summary...
2026-02-26 15:27:11 | metatlas2.rt_align_tools | INFO | RT Alignment Model Summary:
2026-02-26 15:27:11 | metatlas2.rt_align_tools | INFO |   Polynomial degree: 2
2026-02-26 15:27:11 | metatlas2.rt_align_tools | INFO |   R²: 0.9993
2026-02-26 15:27:11 | metatlas2.rt_align_tools | INFO |   RMSE: 0.1380 min
2026-02-26 15:27:11 | metatlas2.rt_align_tools | INFO |   Equation: RT_aligned = 0.302214 + 0.840423 * RT_atlas + 0.008377 * RT_atlas^2
2026-02-26 15:27:11 | metatlas2.rt_align_tools | INFO |   Compounds used for modeling: 19
2026-02-26 15:27:11 | metatlas2.rt_align_tools | INFO | RT Shift Statistics (across all aligned compounds):
2026-02-26 15:27:11 | metatlas2.rt_align_tools | INFO |   Min RT shift: -0.4577 min
2026-02-26 15:27:11 | metatlas2.rt_align_tools | INFO |   Max RT shift: 0.1377 min
2026-02-26 15:27:11 | metatlas2.rt_align_tools | INFO |   Median RT shift: -0.2734 min
2026-02-26 15:27:11 | metatlas2.workflow_objects | INFO | RT alignment procedure complete for RT alignment number 0 and chromatography HILICZ!