In [1]:
import sys
import pandas as pd
pd.options.display.max_colwidth = 600

sys.path.append('/Users/BKieft/Metabolomics/metatlas2/metatlas2')
import logging_config as lcf
import logging
import workflow_objects as wfo
import load_tools as ldt

In [2]:
# Set up logging with level
log_level = logging.INFO
lcf.setup_logging(log_level=log_level)
logger = lcf.get_logger('auto_identification', log_level=log_level)

In [3]:
# Load configuration files
ANALYSIS_CONFIG = ldt.load_metatlas2_config("/Users/BKieft/Metabolomics/metatlas2/configs/analysis.yaml")

2026-02-26 12:24:37 | metatlas2.load_tools | INFO | Loaded metatlas2 configuration from /Users/BKieft/Metabolomics/metatlas2/configs/analysis.yaml

In [4]:
# Set up analysis parameters
PROJECT_NAME = "20260106_JGI_LP-AC_510770_StrigoArab_final_EXP120B_HILICZ_USHXG03402"
ANALYSIS_ATLAS = "atl-rta-istd-hilicz-pos-5565214be7a14d70a1fad0062a351e02"
RT_ALIGN_NUM = 0
ANALYSIS_NUM = 1

In [5]:
# Auto Identifications
wfo.run_auto_identification(
    config=ANALYSIS_CONFIG,
    project_name=PROJECT_NAME,
    rt_alignment_number=RT_ALIGN_NUM,
    analysis_number=ANALYSIS_NUM,
    analysis_atlas=ANALYSIS_ATLAS
)

2026-02-26 12:24:37 | metatlas2.workflow_objects | INFO | Setting up AutoIdentification object for RT alignment number 0, analysis number 1 for project 20260106_JGI_LP-AC_510770_StrigoArab_final_EXP120B_HILICZ_USHXG03402...
2026-02-26 12:24:37 | metatlas2.workflow_objects | INFO | Setting up workflow paths...
2026-02-26 12:24:37 | metatlas2.workflow_objects | INFO | Checking for existing Auto Identification results within RT Alignment number 0 and analysis number 1...
2026-02-26 12:24:37 | metatlas2.database_interact | INFO | No existing AutoIdentification results found for RT alignment number 0 and analysis number 1. Proceeding.
2026-02-26 12:24:37 | metatlas2.workflow_objects | INFO | Retrieving all LCMS runs for project...
2026-02-26 12:24:37 | metatlas2.database_interact | INFO | Retrieved 34 LC/MS run files from database with filters: file_types=None, chromatography=None, polarity=None, format=parquet
2026-02-26 12:24:37 | metatlas2.workflow_objects | INFO | Loading atlas with UID atl-rta-istd-hilicz-pos-5565214be7a14d70a1fad0062a351e02 from database...
2026-02-26 12:24:37 | metatlas2.database_interact | INFO | Attached main database for compound metadata
2026-02-26 12:24:37 | metatlas2.database_interact | INFO | Retrieved 65 compounds for atlas atl-rta-istd-hilicz-pos-5565214be7a14d70a1fad0062a351e02 (Default HILICZ ISTD Atlas Positive (RT aligned))

,atlas_uid,atlas_name,atlas_description,chromatography,polarity,analysis_type,atlas_type,compound_uid,compound_name,inchi_key,inchi,adduct,mz,rt_peak,rt_min,rt_max,mz_tolerance,mz_rt_uid,rt_alignment_applied,manual_curation_applied
0,atl-rta-istd-hilicz-pos-5565214be7a14d70a1fad0062a351e02,Default HILICZ ISTD Atlas Positive (RT aligned),RT-aligned version of Default HILICZ ISTD Atlas Positive,HILICZ,POS,ISTD,RT-ALIGNED,cmp-9009d2dc642e45f492a0c694130d183c,ABMBA (unlabeled),LCMZECCEEOQWLQ-UHFFFAOYSA-N,"InChI=1S/C8H8BrNO2/c1-4-2-5(8(11)12)7(10)6(9)3-4/h2-3H,10H2,1H3,(H,11,12)",[M+H]+,229.981094,1.231498,0.974626,1.489877,5.0,mzrt-exp-183ad35babea48cea87f9fb33bb2ea54,True,False
1,atl-rta-istd-hilicz-pos-5565214be7a14d70a1fad0062a351e02,Default HILICZ ISTD Atlas Positive (RT aligned),RT-aligned version of Default HILICZ ISTD Atlas Positive,HILICZ,POS,ISTD,RT-ALIGNED,cmp-61cd678c69d54b5cb1140287e999bce0,nicotinamide (U - 13C),DFPAKSUCGFBDDF-IDEBNGHGSA-N,"InChI=1S/C6H6N2O/c7-6(9)5-2-1-3-8-4-5/h1-4H,(H2,7,9)/i1+1,2+1,3+1,4+1,5+1,6+1",[M+H]+,129.075424,1.276848,1.019712,1.535492,5.0,mzrt-exp-00ccb9cf6b664103bece076884c2f913,True,False
2,atl-rta-istd-hilicz-pos-5565214be7a14d70a1fad0062a351e02,Default HILICZ ISTD Atlas Positive (RT aligned),RT-aligned version of Default HILICZ ISTD Atlas Positive,HILICZ,POS,ISTD,RT-ALIGNED,cmp-6193b5303d15443383f738d79efce13a,nicotinamide (unlabeled),DFPAKSUCGFBDDF-UHFFFAOYSA-N,"InChI=1S/C6H6N2O/c7-6(9)5-2-1-3-8-4-5/h1-4H,(H2,7,9)",[M+H]+,123.055290,1.276848,1.019712,1.535492,5.0,mzrt-exp-d28190c690ad41ff8cd678d40e8e8e57,True,False
3,atl-rta-istd-hilicz-pos-5565214be7a14d70a1fad0062a351e02,Default HILICZ ISTD Atlas Positive (RT aligned),RT-aligned version of Default HILICZ ISTD Atlas Positive,HILICZ,POS,ISTD,RT-ALIGNED,cmp-4305ab24bdc9467c970b2175d8c8eb6e,"thymine (U - 13C, 15N)",RWQNBRDOKXIBIV-BNUYUSEDSA-N,"InChI=1S/C5H6N2O2/c1-3-2-6-5(9)7-4(3)8/h2H,1H3,(H2,6,7,8,9)/i1+1,2+1,3+1,4+1,5+1,6+1,7+1",[M+H]+,134.061035,1.370339,1.112657,1.629530,5.0,mzrt-exp-82a758ce25ca4335bba8f35742f21aaf,True,False
4,atl-rta-istd-hilicz-pos-5565214be7a14d70a1fad0062a351e02,Default HILICZ ISTD Atlas Positive (RT aligned),RT-aligned version of Default HILICZ ISTD Atlas Positive,HILICZ,POS,ISTD,RT-ALIGNED,cmp-10025527f79b47fe84d7ff2fade14405,thymine (unlabeled),RWQNBRDOKXIBIV-UHFFFAOYSA-N,"InChI=1S/C5H6N2O2/c1-3-2-6-5(9)7-4(3)8/h2H,1H3,(H2,6,7,8,9)",[M+H]+,127.050201,1.370339,1.112657,1.629530,5.0,mzrt-exp-05106476768241f498d310200417291d,True,False

2026-02-26 12:24:37 | metatlas2.workflow_objects | INFO | Validating atlas Default HILICZ ISTD Atlas Positive (RT aligned) (UID: atl-rta-istd-hilicz-pos-5565214be7a14d70a1fad0062a351e02) with 65 compounds...
2026-02-26 12:24:37 | metatlas2.workflow_objects | INFO | Atlas passed validation!
2026-02-26 12:24:37 | metatlas2.workflow_objects | INFO | Loading workflow parameters for targeted analysis from config...
2026-02-26 12:24:37 | metatlas2.workflow_objects | INFO | Finding LCMSRuns matching criteria for auto-identification...
2026-02-26 12:24:37 | metatlas2.lcmsruns_tools | INFO | Filtering 34 LCMS runs with parameters: file_type=['experimental', 'istd', 'exctrl', 'refstd'], file_format=parquet, chromatography=HILIC, polarity=positive...
2026-02-26 12:24:37 | metatlas2.lcmsruns_tools | INFO | Filtered to 13 out of 34 total files.
2026-02-26 12:24:37 | metatlas2.workflow_objects | INFO | Passing Atlas and LCMSRuns to data extractor...
2026-02-26 12:24:37 | metatlas2.extract_data_from_parquet | INFO | Starting data extraction based on atl-rta-istd-hilicz-pos-5565214be7a14d70a1fad0062a351e02 (Default HILICZ ISTD Atlas Positive (RT aligned)) for stage 'auto_identification' from 13 LCMS runs...
2026-02-26 12:24:37 | metatlas2.extract_data_from_parquet | INFO | Initiating an experimental data object to hold results during analysis...
2026-02-26 12:24:37 | metatlas2.extract_data_from_parquet | INFO | Starting data extraction for 65 compounds from 13 project files...
2026-02-26 12:24:37 | metatlas2.extract_data_from_parquet | INFO | Using ppm_tolerance=5.0 and extra_time=1.0 for data extraction.
2026-02-26 12:24:37 | metatlas2.extract_data_from_parquet | INFO | Using parallel processing with 8 workers...

Extracting data from parquet files:   0%|          | 0/13 [00:00<?, ?it/s]

2026-02-26 12:24:50 | metatlas2.workflow_objects | INFO | Passing ExperimentalData to MS2 hit finder...
2026-02-26 12:24:50 | metatlas2.load_tools | INFO | Loading reference spectra from /Users/BKieft/Metabolomics/metatlas_lite_data/databases/msms_refs/msms_refs_no_inosine15n.tab...
2026-02-26 12:24:50 | metatlas2.load_tools | INFO |     Number of total references: 1584
2026-02-26 12:24:50 | metatlas2.load_tools | INFO |     Number of unique InChI keys: 64
2026-02-26 12:24:50 | metatlas2.ms2_hit_detection | INFO | Finding MS2 hits using reference database with 1584 entries...
2026-02-26 12:24:50 | metatlas2.ms2_hit_detection | INFO | Prepared hit detection input for 63 files with MS2 data
2026-02-26 12:24:50 | metatlas2.ms2_hit_detection | INFO | Using parallel processing with 8 workers for hit detection...

Finding MS2 hits:   0%|          | 0/63 [00:00<?, ?it/s]

2026-02-26 12:25:05 | metatlas2.ms2_hit_detection | INFO | Hit detection complete: 63 compounds with reference hits and 4392 total hits
2026-02-26 12:25:05 | metatlas2.workflow_objects | INFO | Passing ExperimentalData and Atlas to ManualCuration creator...

Processing atlas compounds:   0%|          | 0/65 [00:00<?, ?compound/s]

2026-02-26 12:25:07 | metatlas2.workflow_objects | INFO | Passing finalized AutoIdentification object to database saver...
2026-02-26 12:25:07 | metatlas2.database_interact | INFO | Preparing AutoIdentification results for database save...
2026-02-26 12:25:08 | metatlas2.database_interact | INFO | Checking for identical ManualCuration records before database insert...
2026-02-26 12:25:08 | metatlas2.database_interact | INFO | Performing bulk database inserts...
2026-02-26 12:25:08 | metatlas2.database_interact | INFO | Inserting 65 compound metadata records...
2026-02-26 12:25:08 | metatlas2.database_interact | INFO | Inserting 4392 MS2 hits records...
2026-02-26 12:25:11 | metatlas2.database_interact | INFO | Inserting 29738 MS1 raw data records...
2026-02-26 12:25:22 | metatlas2.database_interact | INFO | Inserting 298 MS2 raw data records...
2026-02-26 12:25:22 | metatlas2.database_interact | INFO | Database save complete.
2026-02-26 12:25:22 | metatlas2.workflow_objects | INFO | Passing AutoIdentification object to summary generator...

,inchi_key,adduct,MS1 datapoints,MS2 datapoints,MS2 hits
0,LCMZECCEEOQWLQ-UHFFFAOYSA-N,[M+H]+,740,199,150
1,DFPAKSUCGFBDDF-IDEBNGHGSA-N,[M+H]+,194,0,0
2,DFPAKSUCGFBDDF-UHFFFAOYSA-N,[M+H]+,979,0,0
3,RWQNBRDOKXIBIV-BNUYUSEDSA-N,[M+H]+,55,0,0
4,RWQNBRDOKXIBIV-UHFFFAOYSA-N,[M+H]+,42,0,0
...,...,...,...,...,...
60,LEVWYRKDKASIDU-IMJSIDKUSA-N,[M+H]+,0,0,0
61,ODKSFYDXXFIFQN-GZYYCROJSA-N,[M+H]+,1354,253,154
62,ODKSFYDXXFIFQN-BYPYZUCNSA-N,[M+H]+,133,9,118
63,KDXKERNSBIXSRK-JMKXWGMHSA-N,[M+H]+,318,131,77
64,KDXKERNSBIXSRK-YFKPBYRVSA-N,[M+H]+,28,0,0