In [1]:
import sys
import pandas as pd
pd.options.display.max_colwidth = 600

sys.path.append('/Users/BKieft/Metabolomics/metatlas2/metatlas2')
import logging_config as lcf
import logging
import workflow_objects as wfo
import load_tools as ldt

In [2]:
# Set up logging with level
log_level = logging.INFO
lcf.setup_logging(log_level=log_level)
logger = lcf.get_logger('targeted_workflow', log_level=log_level)

In [3]:
# Load configuration files
ANALYSIS_CONFIG = ldt.load_metatlas2_config("/Users/BKieft/Metabolomics/metatlas2/configs/analysis.yaml")

2026-02-19 16:04:20 | metatlas2.load_tools | INFO | Loaded metatlas2 configuration from /Users/BKieft/Metabolomics/metatlas2/configs/analysis.yaml

In [4]:
# Set up analysis parameters
PROJECT_NAME = "20260106_JGI_LP-AC_510770_StrigoArab_final_EXP120B_HILICZ_USHXG03402"

ANALYSIS_ATLAS = "atl-rta-istd-hilicz-pos-e021f483b9c74abcb920231f5cb243b3"

RT_ALIGN_NUM = 0
ANALYSIS_NUM = 0

In [5]:
# Auto Identifications
wfo.run_auto_identification(
    project_name=PROJECT_NAME,
    config=ANALYSIS_CONFIG,
    rt_alignment_number=RT_ALIGN_NUM,
    analysis_number=ANALYSIS_NUM,
    analysis_atlas=ANALYSIS_ATLAS
)

2026-02-19 16:04:20 | metatlas2.workflow_objects | INFO | Setting up workflow paths for Auto Identification stage...
2026-02-19 16:04:20 | metatlas2.workflow_objects | INFO | Loading target atlas...
2026-02-19 16:04:20 | metatlas2.database_interact | INFO | Attached main database for compound metadata
2026-02-19 16:04:20 | metatlas2.database_interact | INFO | Retrieved 65 compounds for atlas atl-rta-istd-hilicz-pos-e021f483b9c74abcb920231f5cb243b3 (Default HILICZ ISTD Atlas Positive (RT aligned))

,atlas_uid,atlas_name,atlas_description,chromatography,polarity,analysis_type,atlas_type,compound_uid,compound_name,inchi_key,...,adduct,mz,rt_peak,rt_min,rt_max,mz_tolerance,mz_rt_uid,rt_alignment_applied,manual_curation_applied,label
0,atl-rta-istd-hilicz-pos-e021f483b9c74abcb920231f5cb243b3,Default HILICZ ISTD Atlas Positive (RT aligned),RT-aligned version of Default HILICZ ISTD Atlas Positive,HILICZ,POS,ISTD,RT-ALIGNED,cmp-a49bcbf3d8834b28977942d1f5d16b1e,ABMBA (unlabeled),LCMZECCEEOQWLQ-UHFFFAOYSA-N,...,[M+H]+,229.981094,1.227322,0.959749,1.495809,5.0,mzrt-exp-7e28c6dc64e34f40a1efd0c22c71e596,True,False,ABMBA (unlabeled)
1,atl-rta-istd-hilicz-pos-e021f483b9c74abcb920231f5cb243b3,Default HILICZ ISTD Atlas Positive (RT aligned),RT-aligned version of Default HILICZ ISTD Atlas Positive,HILICZ,POS,ISTD,RT-ALIGNED,cmp-a20afcdf1e3f4ea29f17f94690db45e7,nicotinamide (U - 13C),DFPAKSUCGFBDDF-IDEBNGHGSA-N,...,[M+H]+,129.075424,1.274494,1.006760,1.543142,5.0,mzrt-exp-dc89b1bacd774b09bac2c4496632319e,True,False,nicotinamide (U - 13C)
2,atl-rta-istd-hilicz-pos-e021f483b9c74abcb920231f5cb243b3,Default HILICZ ISTD Atlas Positive (RT aligned),RT-aligned version of Default HILICZ ISTD Atlas Positive,HILICZ,POS,ISTD,RT-ALIGNED,cmp-dcc51112e96a4ac2aa5566fb72c7bc1f,nicotinamide (unlabeled),DFPAKSUCGFBDDF-UHFFFAOYSA-N,...,[M+H]+,123.055290,1.274494,1.006760,1.543142,5.0,mzrt-exp-039bd7ec0ede4bab8fbddd3f414e2bb0,True,False,nicotinamide (unlabeled)
3,atl-rta-istd-hilicz-pos-e021f483b9c74abcb920231f5cb243b3,Default HILICZ ISTD Atlas Positive (RT aligned),RT-aligned version of Default HILICZ ISTD Atlas Positive,HILICZ,POS,ISTD,RT-ALIGNED,cmp-07374967578c4d03a77c5293e63c5168,"thymine (U - 13C, 15N)",RWQNBRDOKXIBIV-BNUYUSEDSA-N,...,[M+H]+,134.061035,1.371676,1.103612,1.640656,5.0,mzrt-exp-1be5132e9ba544efbf5feb2e9a0c9c6b,True,False,"thymine (U - 13C, 15N)"
4,atl-rta-istd-hilicz-pos-e021f483b9c74abcb920231f5cb243b3,Default HILICZ ISTD Atlas Positive (RT aligned),RT-aligned version of Default HILICZ ISTD Atlas Positive,HILICZ,POS,ISTD,RT-ALIGNED,cmp-74a82fb2d69643b4a32fe16afedcf4e9,thymine (unlabeled),RWQNBRDOKXIBIV-UHFFFAOYSA-N,...,[M+H]+,127.050201,1.371676,1.103612,1.640656,5.0,mzrt-exp-8c6c501735814bfe885b99116648194a,True,False,thymine (unlabeled)

HILICZ
POS
ISTD
atl-rta-istd-hilicz-pos-e021f483b9c74abcb920231f5cb243b3
Default HILICZ ISTD Atlas Positive (RT aligned)
RT-aligned version of Default HILICZ ISTD Atlas Positive
RT-ALIGNED
2026-02-19 16:04:20 | metatlas2.workflow_objects | INFO | Setting up targeted analysis parameters from configuration...
2026-02-19 16:04:20 | metatlas2.workflow_objects | INFO | Loading experimental files from project database...
2026-02-19 16:04:20 | metatlas2.database_interact | INFO | Retrieved 13 LC/MS run files from database with filters: file_types=['experimental', 'istd', 'exctrl'], chromatography=HILIC, polarity=positive, format=parquet
2026-02-19 16:04:20 | metatlas2.database_interact | INFO | File counts by category:
2026-02-19 16:04:20 | metatlas2.database_interact | INFO |   experimental: 8 files
2026-02-19 16:04:21 | metatlas2.database_interact | INFO |   istd: 2 files
2026-02-19 16:04:21 | metatlas2.database_interact | INFO |   exctrl: 3 files
2026-02-19 16:04:21 | metatlas2.workflow_objects | INFO | Extracting EIC and MS2 data from parquet files using Atlas object...
2026-02-19 16:04:21 | metatlas2.extract_data_from_parquet | INFO | Initiate an experimental data object to hold results during analysis...
2026-02-19 16:04:21 | metatlas2.extract_data_from_parquet | INFO | Starting data extraction for 65 compounds from 13 project files...
2026-02-19 16:04:21 | metatlas2.extract_data_from_parquet | INFO | Using ppm_tolerance=5.0 and extra_time=0.0 for data extraction.
2026-02-19 16:04:21 | metatlas2.extract_data_from_parquet | INFO | Using parallel processing with 8 workers...

Extracting data from parquet files:   0%|          | 0/13 [00:00<?, ?it/s]

2026-02-19 16:04:27 | metatlas2.workflow_objects | INFO | Finding MS2 reference hits...
2026-02-19 16:04:27 | metatlas2.load_tools | INFO | Loading reference spectra from /Users/BKieft/Metabolomics/metatlas_lite_data/databases/msms_refs/msms_refs_no_inosine15n.tab...
2026-02-19 16:04:27 | metatlas2.load_tools | INFO |     Number of total references: 1584
2026-02-19 16:04:27 | metatlas2.load_tools | INFO |     Number of unique InChI keys: 64
2026-02-19 16:04:27 | metatlas2.ms2_hit_detection | INFO | Finding MS2 hits using reference database with 1584 entries...
2026-02-19 16:04:27 | metatlas2.ms2_hit_detection | INFO | Prepared hit detection input for 56 files with MS2 data
2026-02-19 16:04:27 | metatlas2.ms2_hit_detection | INFO | Using parallel processing with 8 workers for hit detection...

Finding MS2 hits:   0%|          | 0/56 [00:00<?, ?it/s]

2026-02-19 16:04:34 | metatlas2.ms2_hit_detection | INFO | Hit detection complete: 56 compounds with reference hits and 2423 total hits
2026-02-19 16:04:34 | metatlas2.workflow_objects | INFO | Calculating MS1 and MS2 summary statistics for each compound and file...
2026-02-19 16:04:34 | metatlas2.workflow_objects | INFO | Saving experimental data to project database...
2026-02-19 16:04:34 | metatlas2.database_interact | INFO | Preparing complete analysis data for database save...
2026-02-19 16:04:34 | metatlas2.database_interact | INFO | Performing bulk database inserts...
2026-02-19 16:04:34 | metatlas2.database_interact | INFO | Complete analysis data saved to database. Summary:

Empty DataFrame
Columns: []
Index: []

2026-02-19 16:04:34 | metatlas2.workflow_objects | INFO | Auto Identification stage complete for rt alignment number 0 and analysis number 0!