In [1]:
import sys
import pandas as pd
sys.path.append('/Users/BKieft/Metabolomics/metatlas2')
import metatlas2.database_interact as dbi
import metatlas2.pubchem_retrieval as pcr
import metatlas2.load_tools as ldt
import metatlas2.lcmsruns_tools as lrt
import metatlas2.ms1_ms2_analysis as msa
import metatlas2.rt_align_tools as rat
import metatlas2.targeted_analysis as tga
import metatlas2.targeted_gui as tgi
import metatlas2.data_classes as dc  # Add this import
pd.options.display.max_colwidth = 300

In [2]:
# Required: load config file
CONFIG = ldt.load_metatlas_config("/Users/BKieft/Metabolomics/metatlas2/configs/metatlas2_config.yaml")
# Required: table with compounds to add to db. Minimally, must have columns 'inchi_key' and 'label'
COMPOUND_INPUTS = ["/Users/BKieft/Metabolomics/metatlas2/data/atlas_tables/HILICZ/HILICZ_QC_POS.tsv",
                   "/Users/BKieft/Metabolomics/metatlas2/data/atlas_tables/HILICZ/HILICZ_ISTD_POS.tsv", 
                   "/Users/BKieft/Metabolomics/metatlas2/data/atlas_tables/HILICZ/HILICZ_ISTD_NEG.tsv",
                   "/Users/BKieft/Metabolomics/metatlas2/data/atlas_tables/HILICZ/HILICZ_EMA_POS.tsv",
                   "/Users/BKieft/Metabolomics/metatlas2/data/atlas_tables/HILICZ/HILICZ_EMA_NEG.tsv"]
# Required: table of compounds; minimally, must have columns 'inchi_key', 'chromatography', 'polarity', 'rt_peak', 'mz', 'adduct'
ATLAS_INPUTS = ["/Users/BKieft/Metabolomics/metatlas2/data/atlas_tables/HILICZ/HILICZ_ISTD_POS.tsv",
                "/Users/BKieft/Metabolomics/metatlas2/data/atlas_tables/HILICZ/HILICZ_QC_POS.tsv"]
# Required: name of atlas (does not have to be unique) 
ATLAS_NAMES = ["HILIC Positive ISTD Default", "HILIC Positive QC Default"]
# Optional: description of atlas
ATLAS_DESC = [f"Default ISTD compounds for HILIC Positive", f"Default QC compounds for HILIC Positive"]
# Required: Project name
PROJECT_NAME = "20250707_JGI_MS_510172_SedRhizVegOut_final_IQX_HILICZ_USHXG02519"
# Required: paths based on config
PROJECT_FILES_PATH = f"{CONFIG['paths']['projects_dir']}/{PROJECT_NAME}/lcmsruns"
PROJECT_DB_PATH = f"{CONFIG['paths']['projects_dir']}/{PROJECT_NAME}/{PROJECT_NAME}.duckdb"
# Required: path to id report
REPORT_PATH = f'/Users/BKieft/Downloads/{PROJECT_NAME}_comprehensive_report.xlsx'

In [3]:
new_main_database = True
new_atlases = True
new_rt_alignment = True
new_analysis = True

In [4]:
if new_main_database is True:
    dbi.create_metatlas_database(CONFIG)
    for COMPOUNDS_INPUT in COMPOUND_INPUTS:
        compounds_df = ldt.load_compound_input(COMPOUNDS_INPUT)
        pcr.retrieve_pubchem_info(compounds_df, CONFIG)
        dbi.add_compounds_to_db(compounds_df, CONFIG, COMPOUNDS_INPUT)
    dbi.validate_database(CONFIG)

Warning! Overwrite is True and database exists. Giving 30 seconds before overwriting to abort.
Deleted existing database at /Users/BKieft/Metabolomics/metatlas2/data/databases/metatlas.duckdb and proceeding...
Main metatlas database created at /Users/BKieft/Metabolomics/metatlas2/data/databases/metatlas.duckdb
Loaded 20 compounds from /Users/BKieft/Metabolomics/metatlas2/data/atlas_tables/HILICZ/HILICZ_QC_POS.tsv
Loaded global PubChem cache with 482 entries from /Users/BKieft/Metabolomics/metatlas2/data/databases/pubchem_cache/pubchem_global_cache.pkl
Compounds already in cache: 20
Compounds needing PubChem lookup: 0
All compounds already in cache!

Some compounds not found in PubChem: ['HEBKCHPVOIAQTA-OWTCIZGHSA-N', 'HEBKCHPVOIAQTA-ZXFHETKHSA-N', 'HEBKCHPVOIAQTA-FCLZTKDGSA-N', 'HEBKCHPVOIAQTA-QSYSQFBZSA-N']...
These will be created with minimal information from the input table.

PubChem data retrieval complete!
    Total compounds in global cache: 482
    Successful PubChem retrievals in cache: 478
    Failed retrievals in cache: 4
Adding 20 compounds to database: /Users/BKieft/Metabolomics/metatlas2/data/databases/metatlas.duckdb
Loaded global PubChem cache with 482 entries from /Users/BKieft/Metabolomics/metatlas2/data/databases/pubchem_cache/pubchem_global_cache.pkl
Preparing batch data...

Preparing compounds:   0%|          | 0/20 [00:00<?, ?it/s]

Batch inserting 20 compounds...
Checking for duplicate references and batch inserting...

Compounds added successfully!
   Total compounds in database: 20
   New compounds created: 20
   Total RT/MZ references in database: 20
   New RT/MZ references created: 20
Loaded 65 compounds from /Users/BKieft/Metabolomics/metatlas2/data/atlas_tables/HILICZ/HILICZ_ISTD_POS.tsv
Loaded global PubChem cache with 482 entries from /Users/BKieft/Metabolomics/metatlas2/data/databases/pubchem_cache/pubchem_global_cache.pkl
Compounds already in cache: 65
Compounds needing PubChem lookup: 0
All compounds already in cache!

Some compounds not found in PubChem: ['HEBKCHPVOIAQTA-OWTCIZGHSA-N', 'HEBKCHPVOIAQTA-ZXFHETKHSA-N', 'HEBKCHPVOIAQTA-FCLZTKDGSA-N', 'HEBKCHPVOIAQTA-QSYSQFBZSA-N']...
These will be created with minimal information from the input table.

PubChem data retrieval complete!
    Total compounds in global cache: 482
    Successful PubChem retrievals in cache: 478
    Failed retrievals in cache: 4
Adding 65 compounds to database: /Users/BKieft/Metabolomics/metatlas2/data/databases/metatlas.duckdb
Loaded global PubChem cache with 482 entries from /Users/BKieft/Metabolomics/metatlas2/data/databases/pubchem_cache/pubchem_global_cache.pkl
Found 20 existing compounds in database. Not creating duplicates.
Preparing batch data...

Preparing compounds:   0%|          | 0/65 [00:00<?, ?it/s]

Batch inserting 45 compounds...
Checking for duplicate references and batch inserting...

Compounds added successfully!
   Total compounds in database: 65
   New compounds created: 45
   Compounds skipped (already existed): 20
   Total RT/MZ references in database: 65
   New RT/MZ references created: 45
   RT/MZ references skipped (duplicates): 20
Loaded 85 compounds from /Users/BKieft/Metabolomics/metatlas2/data/atlas_tables/HILICZ/HILICZ_ISTD_NEG.tsv
Loaded global PubChem cache with 482 entries from /Users/BKieft/Metabolomics/metatlas2/data/databases/pubchem_cache/pubchem_global_cache.pkl
Compounds already in cache: 83
Compounds needing PubChem lookup: 0
All compounds already in cache!

Some compounds not found in PubChem: ['HEBKCHPVOIAQTA-OWTCIZGHSA-N', 'HEBKCHPVOIAQTA-ZXFHETKHSA-N', 'HEBKCHPVOIAQTA-FCLZTKDGSA-N', 'HEBKCHPVOIAQTA-QSYSQFBZSA-N']...
These will be created with minimal information from the input table.

PubChem data retrieval complete!
    Total compounds in global cache: 482
    Successful PubChem retrievals in cache: 478
    Failed retrievals in cache: 4
Adding 83 compounds to database: /Users/BKieft/Metabolomics/metatlas2/data/databases/metatlas.duckdb
Loaded global PubChem cache with 482 entries from /Users/BKieft/Metabolomics/metatlas2/data/databases/pubchem_cache/pubchem_global_cache.pkl
Found 65 existing compounds in database. Not creating duplicates.
Preparing batch data...
Checking for duplicate references and batch inserting...

Compounds added successfully!
   Total compounds in database: 65
   New compounds created: 45
   Compounds skipped (already existed): 20
   Total RT/MZ references in database: 65
   New RT/MZ references created: 45
   RT/MZ references skipped (duplicates): 20
Loaded 85 compounds from /Users/BKieft/Metabolomics/metatlas2/data/atlas_tables/HILICZ/HILICZ_ISTD_NEG.tsv
Loaded global PubChem cache with 482 entries from /Users/BKieft/Metabolomics/metatlas2/data/databases/pubchem_cache/pubchem_global_cache.pkl
Compounds already in cache: 83
Compounds needing PubChem lookup: 0
All compounds already in cache!

Some compounds not found in PubChem: ['HEBKCHPVOIAQTA-OWTCIZGHSA-N', 'HEBKCHPVOIAQTA-ZXFHETKHSA-N', 'HEBKCHPVOIAQTA-FCLZTKDGSA-N', 'HEBKCHPVOIAQTA-QSYSQFBZSA-N']...
These will be created with minimal information from the input table.

PubChem data retrieval complete!
    Total compounds in global cache: 482
    Successful PubChem retrievals in cache: 478
    Failed retrievals in cache: 4
Adding 83 compounds to database: /Users/BKieft/Metabolomics/metatlas2/data/databases/metatlas.duckdb
Loaded global PubChem cache with 482 entries from /Users/BKieft/Metabolomics/metatlas2/data/databases/pubchem_cache/pubchem_global_cache.pkl
Found 65 existing compounds in database. Not creating duplicates.
Preparing batch data...

Preparing compounds:   0%|          | 0/85 [00:00<?, ?it/s]

Batch inserting 22 compounds...
Checking for duplicate references and batch inserting...

Compounds added successfully!
   Total compounds in database: 87
   New compounds created: 22
   Compounds skipped (already existed): 63
   Total RT/MZ references in database: 148
   New RT/MZ references created: 83
   RT/MZ references skipped (duplicates): 2
Loaded 373 compounds from /Users/BKieft/Metabolomics/metatlas2/data/atlas_tables/HILICZ/HILICZ_EMA_POS.tsv
Loaded global PubChem cache with 482 entries from /Users/BKieft/Metabolomics/metatlas2/data/databases/pubchem_cache/pubchem_global_cache.pkl
Compounds already in cache: 333
Compounds needing PubChem lookup: 0
All compounds already in cache!

Some compounds not found in PubChem: ['HEBKCHPVOIAQTA-OWTCIZGHSA-N', 'HEBKCHPVOIAQTA-ZXFHETKHSA-N', 'HEBKCHPVOIAQTA-FCLZTKDGSA-N', 'HEBKCHPVOIAQTA-QSYSQFBZSA-N']...
These will be created with minimal information from the input table.

PubChem data retrieval complete!
    Total compounds in global cache: 482
    Successful PubChem retrievals in cache: 478
    Failed retrievals in cache: 4
Adding 333 compounds to database: /Users/BKieft/Metabolomics/metatlas2/data/databases/metatlas.duckdb
Loaded global PubChem cache with 482 entries from /Users/BKieft/Metabolomics/metatlas2/data/databases/pubchem_cache/pubchem_global_cache.pkl
Found 87 existing compounds in database. Not creating duplicates.
Preparing batch data...

Compounds added successfully!
   Total compounds in database: 87
   New compounds created: 22
   Compounds skipped (already existed): 63
   Total RT/MZ references in database: 148
   New RT/MZ references created: 83
   RT/MZ references skipped (duplicates): 2
Loaded 373 compounds from /Users/BKieft/Metabolomics/metatlas2/data/atlas_tables/HILICZ/HILICZ_EMA_POS.tsv
Loaded global PubChem cache with 482 entries from /Users/BKieft/Metabolomics/metatlas2/data/databases/pubchem_cache/pubchem_global_cache.pkl
Compounds already in cache: 333
Compounds needing PubChem lookup: 0
All compounds already in cache!

Some compounds not found in PubChem: ['HEBKCHPVOIAQTA-OWTCIZGHSA-N', 'HEBKCHPVOIAQTA-ZXFHETKHSA-N', 'HEBKCHPVOIAQTA-FCLZTKDGSA-N', 'HEBKCHPVOIAQTA-QSYSQFBZSA-N']...
These will be created with minimal information from the input table.

PubChem data retrieval complete!
    Total compounds in global cache: 482
    Successful PubChem retrievals in cache: 478
    Failed retrievals in cache: 4
Adding 333 compounds to database: /Users/BKieft/Metabolomics/metatlas2/data/databases/metatlas.duckdb
Loaded global PubChem cache with 482 entries from /Users/BKieft/Metabolomics/metatlas2/data/databases/pubchem_cache/pubchem_global_cache.pkl
Found 87 existing compounds in database. Not creating duplicates.
Preparing batch data...

Preparing compounds:   0%|          | 0/373 [00:00<?, ?it/s]

Batch inserting 297 compounds...
Checking for duplicate references and batch inserting...
Checking for duplicate references and batch inserting...

Compounds added successfully!
   Total compounds in database: 384
   New compounds created: 297
   Compounds skipped (already existed): 76
   Total RT/MZ references in database: 487
   New RT/MZ references created: 339
   RT/MZ references skipped (duplicates): 34
Loaded 418 compounds from /Users/BKieft/Metabolomics/metatlas2/data/atlas_tables/HILICZ/HILICZ_EMA_NEG.tsv
Loaded global PubChem cache with 482 entries from /Users/BKieft/Metabolomics/metatlas2/data/databases/pubchem_cache/pubchem_global_cache.pkl
Compounds already in cache: 395
Compounds needing PubChem lookup: 0
All compounds already in cache!

Some compounds not found in PubChem: ['HEBKCHPVOIAQTA-OWTCIZGHSA-N', 'HEBKCHPVOIAQTA-ZXFHETKHSA-N', 'HEBKCHPVOIAQTA-FCLZTKDGSA-N', 'HEBKCHPVOIAQTA-QSYSQFBZSA-N']...
These will be created with minimal information from the input table.

PubChem data retrieval complete!
    Total compounds in global cache: 482
    Successful PubChem retrievals in cache: 478
    Failed retrievals in cache: 4
Adding 395 compounds to database: /Users/BKieft/Metabolomics/metatlas2/data/databases/metatlas.duckdb
Loaded global PubChem cache with 482 entries from /Users/BKieft/Metabolomics/metatlas2/data/databases/pubchem_cache/pubchem_global_cache.pkl
Found 384 existing compounds in database. Not creating duplicates.
Preparing batch data...

Compounds added successfully!
   Total compounds in database: 384
   New compounds created: 297
   Compounds skipped (already existed): 76
   Total RT/MZ references in database: 487
   New RT/MZ references created: 339
   RT/MZ references skipped (duplicates): 34
Loaded 418 compounds from /Users/BKieft/Metabolomics/metatlas2/data/atlas_tables/HILICZ/HILICZ_EMA_NEG.tsv
Loaded global PubChem cache with 482 entries from /Users/BKieft/Metabolomics/metatlas2/data/databases/pubchem_cache/pubchem_global_cache.pkl
Compounds already in cache: 395
Compounds needing PubChem lookup: 0
All compounds already in cache!

Some compounds not found in PubChem: ['HEBKCHPVOIAQTA-OWTCIZGHSA-N', 'HEBKCHPVOIAQTA-ZXFHETKHSA-N', 'HEBKCHPVOIAQTA-FCLZTKDGSA-N', 'HEBKCHPVOIAQTA-QSYSQFBZSA-N']...
These will be created with minimal information from the input table.

PubChem data retrieval complete!
    Total compounds in global cache: 482
    Successful PubChem retrievals in cache: 478
    Failed retrievals in cache: 4
Adding 395 compounds to database: /Users/BKieft/Metabolomics/metatlas2/data/databases/metatlas.duckdb
Loaded global PubChem cache with 482 entries from /Users/BKieft/Metabolomics/metatlas2/data/databases/pubchem_cache/pubchem_global_cache.pkl
Found 384 existing compounds in database. Not creating duplicates.
Preparing batch data...

Preparing compounds:   0%|          | 0/418 [00:00<?, ?it/s]

Batch inserting 98 compounds...
Checking for duplicate references and batch inserting...
Checking for duplicate references and batch inserting...

Compounds added successfully!
   Total compounds in database: 482
   New compounds created: 98
   Compounds skipped (already existed): 320
   Total RT/MZ references in database: 860
   New RT/MZ references created: 373
   RT/MZ references skipped (duplicates): 45

Database Validation:
   Compounds: 482
   RT/MZ References: 860
   Atlases: 0
   Atlas-Compound associations: 0
   Method combinations:
      HILICZ/positive: 404 references
      HILICZ/negative: 456 references

Compounds added successfully!
   Total compounds in database: 482
   New compounds created: 98
   Compounds skipped (already existed): 320
   Total RT/MZ references in database: 860
   New RT/MZ references created: 373
   RT/MZ references skipped (duplicates): 45

Database Validation:
   Compounds: 482
   RT/MZ References: 860
   Atlases: 0
   Atlas-Compound associations: 0
   Method combinations:
      HILICZ/positive: 404 references
      HILICZ/negative: 456 references

In [5]:
if new_atlases is True:
    new_atlas_info = ()
    for ATLAS_INPUT, ATLAS_NAME, ATLAS_DESC in zip(ATLAS_INPUTS, ATLAS_NAMES, ATLAS_DESC):
        atlas_compounds_df = ldt.load_atlas_input(ATLAS_INPUT)
        atlas_uid, atlas_name = dbi.create_atlas_from_compounds(atlas_compounds_df, ATLAS_NAME, ATLAS_DESC, CONFIG)
        new_atlas_info += ((atlas_uid, atlas_name),)
    dbi.validate_database(CONFIG)
    QC_ATLAS_UID = next(uid for uid, name in new_atlas_info if "QC" in name)
    TARGET_ATLAS_UID = next(uid for uid, name in new_atlas_info if "QC" not in name)
else:
    QC_ATLAS_UID = "atl-raw-948261b5838e415f9feb3ef62e19e0f6"
    TARGET_ATLAS_UID = "atl-raw-4239aecf4f51488f9b16b9329d5f8f31"

Loaded 65 atlas entries from /Users/BKieft/Metabolomics/metatlas2/data/atlas_tables/HILICZ/HILICZ_ISTD_POS.tsv
Validating compounds exist in database: /Users/BKieft/Metabolomics/metatlas2/data/databases/metatlas.duckdb
Database contains 482 compounds, searching for missing compounds in input.
Compounds available for atlas: 65
Compounds missing from database: 0

All 65 compounds found in database!
Created new atlas: HILIC Positive ISTD Default (UID: atl-raw-26bd6c4376d847259174fed1e95c329a). Adding compounds...

Atlas creation complete!
   Atlas Name: HILIC Positive ISTD Default
   Atlas UID: atl-raw-26bd6c4376d847259174fed1e95c329a
   Atlas associations created: 65
   Method: HILICZ/positive
Loaded 20 atlas entries from /Users/BKieft/Metabolomics/metatlas2/data/atlas_tables/HILICZ/HILICZ_QC_POS.tsv
Validating compounds exist in database: /Users/BKieft/Metabolomics/metatlas2/data/databases/metatlas.duckdb
Database contains 482 compounds, searching for missing compounds in input.
Compounds available for atlas: 20
Compounds missing from database: 0

All 20 compounds found in database!
Created new atlas: HILIC Positive QC Default (UID: atl-raw-ed8ee50f5647463193d4250a0e650214). Adding compounds...

Atlas creation complete!
   Atlas Name: HILIC Positive QC Default
   Atlas UID: atl-raw-ed8ee50f5647463193d4250a0e650214
   Atlas associations created: 20
   Method: HILICZ/positive

Database Validation:
   Compounds: 482
   RT/MZ References: 860
   Atlases: 2
   Atlas-Compound associations: 85
   Method combinations:
      HILICZ/negative: 456 references
      HILICZ/positive: 404 references
   Available atlases:
      atl-raw-26bd6c4376d847259174fed1e95c329a
            HILIC Positive ISTD Default
            HILICZ positive
            65 compounds
            2025-09-03 14:40:01.449063
      atl-raw-ed8ee50f5647463193d4250a0e650214
            HILIC Positive QC Default
            HILICZ positive
            20 compounds
            2025-09-03 14:40:01.580869

In [6]:
# Debug the QC atlas
print("QC_ATLAS_UID:", QC_ATLAS_UID)

# Check what's in the QC atlas
qc_atlas_compounds = dbi.get_atlas_compounds_table(CONFIG['paths']['main_database'], QC_ATLAS_UID)
print(f"QC Atlas compounds: {len(qc_atlas_compounds)}")
if not qc_atlas_compounds.empty:
    print("Sample compounds:")
    print(qc_atlas_compounds[['compound_name', 'chromatography', 'polarity', 'mz', 'rt_peak']].head())

# Check what QC files we have
try:
    qc_files = dbi.get_files_by_type_from_db(PROJECT_DB_PATH, 'qc')
    print(f"\nQC files found: {len(qc_files)}")
    if not qc_files.empty:
        print("Sample QC files:")
        print(qc_files[['file_path', 'chromatography', 'polarity']].head())
except Exception as e:
    print(f"Error getting QC files: {e}")

# Check configuration
print(f"\nRT alignment tolerances:")
print(f"  m/z: {CONFIG['rt_alignment']['tolerances']['mz']} ppm")
print(f"  RT: {CONFIG['rt_alignment']['tolerances']['rt']} min") 
print(f"  Intensity: {CONFIG['rt_alignment']['tolerances']['i']}")

QC_ATLAS_UID: atl-raw-ed8ee50f5647463193d4250a0e650214
Retrieved 20 compounds from main database for atlas: HILIC Positive QC Default (atl-raw-ed8ee50f5647463193d4250a0e650214)
Atlas chromatography: HILICZ, polarity: positive
QC Atlas compounds: 20
Sample compounds:
            compound_name chromatography  polarity         mz   rt_peak
0       ABMBA (unlabeled)         HILICZ  positive  229.98110  1.093806
1  thymine (U - 13C, 15N)         HILICZ  positive  134.06104  1.255231
2       adenine (U - 15N)         HILICZ  positive  141.04694  2.677602
3  hypoxanthine (U - 15N)         HILICZ  positive  141.03392  3.102967
4       inosine (U - 15N)         HILICZ  positive  273.07618  5.434236

QC files found: 2
Sample QC files:
                                                                                                                                                                                                                                                                       file_path  \
0       /Users/BKieft/Metabolomics/metatlas2/data/test_data/projects/20250707_JGI_MS_510172_SedRhizVegOut_final_IQX_HILICZ_USHXG02519/lcmsruns/20250707_JGI_MS_510172_SedRhizVegOut_final_IQX_HILICZ_USHXG02519_FPS_MS1_2_Winter-RWi_3_Rg70to1050-CE102040norm-rhizo-QC_Run58.h5
1  /Users/BKieft/Metabolomics/metatlas2/data/test_data/projects/20250707_JGI_MS_510172_SedRhizVegOut_final_IQX_HILICZ_USHXG02519/lcmsruns/20250707_JGI_MS_510172_SedRhizVegOut_final_IQX_HILICZ_USHXG02519_FPS_MS1_33_Summer-VSu_6_Rg70to1050-CE102040norm-veg-core-QC_Run107.h5

  chromatography polarity
0          HILIC      FPS
1          HILIC      FPS

RT alignment tolerances:
  m/z: 20.0 ppm
  RT: 1.0 min
  Intensity: 10000.0
Retrieved 20 compounds from main database for atlas: HILIC Positive QC Default (atl-raw-ed8ee50f5647463193d4250a0e650214)
Atlas chromatography: HILICZ, polarity: positive
QC Atlas compounds: 20
Sample compounds:
            compound_name chromatography  polarity         mz   rt_peak
0       ABMBA (unlabeled)         HILICZ  positive  229.98110  1.093806
1  thymine (U - 13C, 15N)         HILICZ  positive  134.06104  1.255231
2       adenine (U - 15N)         HILICZ  positive  141.04694  2.677602
3  hypoxanthine (U - 15N)         HILICZ  positive  141.03392  3.102967
4       inosine (U - 15N)         HILICZ  positive  273.07618  5.434236

QC files found: 2
Sample QC files:
                                                                                                                                                                                                                                                                       file_path  \
0       /Users/BKieft/Metabolomics/metatlas2/data/test_data/projects/20250707_JGI_MS_510172_SedRhizVegOut_final_IQX_HILICZ_USHXG02519/lcmsruns/20250707_JGI_MS_510172_SedRhizVegOut_final_IQX_HILICZ_USHXG02519_FPS_MS1_2_Winter-RWi_3_Rg70to1050-CE102040norm-rhizo-QC_Run58.h5
1  /Users/BKieft/Metabolomics/metatlas2/data/test_data/projects/20250707_JGI_MS_510172_SedRhizVegOut_final_IQX_HILICZ_USHXG02519/lcmsruns/20250707_JGI_MS_510172_SedRhizVegOut_final_IQX_HILICZ_USHXG02519_FPS_MS1_33_Summer-VSu_6_Rg70to1050-CE102040norm-veg-core-QC_Run107.h5

  chromatography polarity
0          HILIC      FPS
1          HILIC      FPS

RT alignment tolerances:
  m/z: 20.0 ppm
  RT: 1.0 min
  Intensity: 10000.0

In [7]:
if new_rt_alignment is True:
    dbi.create_project_database(PROJECT_DB_PATH, CONFIG)
    lcmsrun_files = dbi.save_lcmsruns_to_db(PROJECT_DB_PATH, PROJECT_NAME, PROJECT_FILES_PATH, CONFIG)
    matches_df, matching_stats = msa.extract_and_match_qc_compounds(PROJECT_DB_PATH, QC_ATLAS_UID, CONFIG)
    best_model, model_results, model_stats = rat.build_rt_alignment_model(matches_df, CONFIG)
    ANALYSIS_ATLAS_UID = rat.apply_rt_correction_to_target(PROJECT_DB_PATH, TARGET_ATLAS_UID, CONFIG, best_model, lcmsrun_files, model_results)
else:
    ANALYSIS_ATLAS_UID = "atl-rta-58ded23f08ba48b2abce38a078b8a9b4"

Overwrite is set to True; Deleted existing database at /Users/BKieft/Metabolomics/metatlas2/data/test_data/projects/20250707_JGI_MS_510172_SedRhizVegOut_final_IQX_HILICZ_USHXG02519/20250707_JGI_MS_510172_SedRhizVegOut_final_IQX_HILICZ_USHXG02519.duckdb and proceeding...
Project database created at /Users/BKieft/Metabolomics/metatlas2/data/test_data/projects/20250707_JGI_MS_510172_SedRhizVegOut_final_IQX_HILICZ_USHXG02519/20250707_JGI_MS_510172_SedRhizVegOut_final_IQX_HILICZ_USHXG02519.duckdb
Found 8 .h5 files in /Users/BKieft/Metabolomics/metatlas2/data/test_data/projects/20250707_JGI_MS_510172_SedRhizVegOut_final_IQX_HILICZ_USHXG02519/lcmsruns

Categorizing files:   0%|          | 0/8 [00:00<?, ?it/s]

Saved 8 LCMS runs to database:

Chromatography: HILIC
  Polarity: FPS
    qc: 2 files
    istd: 1 files
    experimental: 1 files
  Polarity: positive
    experimental: 3 files
    exctrl: 1 files
Loading QC files and atlas compounds from databases...
Retrieved 20 compounds from main database for atlas: HILIC Positive QC Default (atl-raw-ed8ee50f5647463193d4250a0e650214)
Atlas chromatography: HILICZ, polarity: positive
Found 2 QC files and 20 QC compounds
Sample compounds from atlas:
  1: ABMBA (unlabeled) - HILICZ/positive - RT: 1.09380632 - m/z: 229.9811
  2: thymine (U - 13C, 15N) - HILICZ/positive - RT: 1.25523106 - m/z: 134.06104
  3: adenine (U - 15N) - HILICZ/positive - RT: 2.677602 - m/z: 141.04694
Sample QC files:
  1: 20250707_JGI_MS_510172_SedRhizVegOut_final_IQX_HILICZ_USHXG02519_FPS_MS1_2_Winter-RWi_3_Rg70to1050-CE102040norm-rhizo-QC_Run58.h5 - HILIC/FPS
  2: 20250707_JGI_MS_510172_SedRhizVegOut_final_IQX_HILICZ_USHXG02519_FPS_MS1_33_Summer-VSu_6_Rg70to1050-CE102040norm-veg-core-QC_Run107.h5 - HILIC/FPS
Extracting MS1 data from QC files...

Extracting MS1 data:   0%|          | 0/2 [00:00<?, ?it/s]

  Intensity filter: 474414 -> 287578 peaks (threshold: 10000.0)
  Extracted 287578 peaks from 20250707_JGI_MS_510172_SedRhizVegOut_final_IQX_HILICZ_USHXG02519_FPS_MS1_2_Winter-RWi_3_Rg70to1050-CE102040norm-rhizo-QC_Run58.h5 (ms1_pos)
  Extracted 287578 peaks from 20250707_JGI_MS_510172_SedRhizVegOut_final_IQX_HILICZ_USHXG02519_FPS_MS1_2_Winter-RWi_3_Rg70to1050-CE102040norm-rhizo-QC_Run58.h5 (ms1_pos)
  Intensity filter: 675587 -> 124042 peaks (threshold: 10000.0)
  Extracted 124042 peaks from 20250707_JGI_MS_510172_SedRhizVegOut_final_IQX_HILICZ_USHXG02519_FPS_MS1_2_Winter-RWi_3_Rg70to1050-CE102040norm-rhizo-QC_Run58.h5 (ms1_neg)
  Intensity filter: 675587 -> 124042 peaks (threshold: 10000.0)
  Extracted 124042 peaks from 20250707_JGI_MS_510172_SedRhizVegOut_final_IQX_HILICZ_USHXG02519_FPS_MS1_2_Winter-RWi_3_Rg70to1050-CE102040norm-rhizo-QC_Run58.h5 (ms1_neg)
  Intensity filter: 475466 -> 274055 peaks (threshold: 10000.0)
  Extracted 274055 peaks from 20250707_JGI_MS_510172_SedRhizVegOut_final_IQX_HILICZ_USHXG02519_FPS_MS1_33_Summer-VSu_6_Rg70to1050-CE102040norm-veg-core-QC_Run107.h5 (ms1_pos)
  Intensity filter: 645572 -> 118235 peaks (threshold: 10000.0)
  Extracted 118235 peaks from 20250707_JGI_MS_510172_SedRhizVegOut_final_IQX_HILICZ_USHXG02519_FPS_MS1_33_Summer-VSu_6_Rg70to1050-CE102040norm-veg-core-QC_Run107.h5 (ms1_neg)
Total MS1 peaks extracted: 803,910
MS1 data polarity distribution: {'positive': 561633, 'negative': 242277}
MS1 data chromatography distribution: {'HILIC': 803910}

Matching QC compounds to extracted peaks...
  Intensity filter: 475466 -> 274055 peaks (threshold: 10000.0)
  Extracted 274055 peaks from 20250707_JGI_MS_510172_SedRhizVegOut_final_IQX_HILICZ_USHXG02519_FPS_MS1_33_Summer-VSu_6_Rg70to1050-CE102040norm-veg-core-QC_Run107.h5 (ms1_pos)
  Intensity filter: 645572 -> 118235 peaks (threshold: 10000.0)
  Extracted 118235 peaks from 20250707_JGI_MS_510172_SedRhizVegOut_final_IQX_HILICZ_USHXG02519_FPS_MS1_33_Summer-VSu_6_Rg70to1050-CE102040norm-veg-core-QC_Run107.h5 (ms1_neg)
Total MS1 peaks extracted: 803,910
MS1 data polarity distribution: {'positive': 561633, 'negative': 242277}
MS1 data chromatography distribution: {'HILIC': 803910}

Matching QC compounds to extracted peaks...

Matching compounds:   0%|          | 0/20 [00:00<?, ?it/s]

  Processing compound 1: ABMBA (unlabeled)
    Target: HILIC/positive, m/z=229.9811, RT=1.09
    After chromatography filter (HILIC): 803910 peaks
    After chromatography filter (HILIC): 803910 peaks
    After polarity filter (positive): 803910 peaks
    After m/z and RT filters: 30 peaks
  Processing compound 2: thymine (U - 13C, 15N)
    Target: HILIC/positive, m/z=134.0610, RT=1.26
    After polarity filter (positive): 803910 peaks
    After m/z and RT filters: 30 peaks
  Processing compound 2: thymine (U - 13C, 15N)
    Target: HILIC/positive, m/z=134.0610, RT=1.26
    After chromatography filter (HILIC): 803910 peaks
    After chromatography filter (HILIC): 803910 peaks
    After polarity filter (positive): 803910 peaks
    After m/z and RT filters: 19 peaks
  Processing compound 3: adenine (U - 15N)
    Target: HILIC/positive, m/z=141.0469, RT=2.68
    After polarity filter (positive): 803910 peaks
    After m/z and RT filters: 19 peaks
  Processing compound 3: adenine (U - 15N)
    Target: HILIC/positive, m/z=141.0469, RT=2.68
    After chromatography filter (HILIC): 803910 peaks
    After chromatography filter (HILIC): 803910 peaks
    After polarity filter (positive): 803910 peaks
    After m/z and RT filters: 224 peaks
    After polarity filter (positive): 803910 peaks
    After m/z and RT filters: 224 peaks
    After chromatography filter (HILIC): 803910 peaks
    After chromatography filter (HILIC): 803910 peaks
    After polarity filter (positive): 803910 peaks
    After m/z and RT filters: 207 peaks
    After polarity filter (positive): 803910 peaks
    After m/z and RT filters: 207 peaks
    After chromatography filter (HILIC): 803910 peaks
    After chromatography filter (HILIC): 803910 peaks
    After polarity filter (positive): 803910 peaks
    After polarity filter (positive): 803910 peaks
    After m/z and RT filters: 97 peaks
    After chromatography filter (HILIC): 803910 peaks
    After m/z and RT filters: 97 peaks
    After chromatography filter (HILIC): 803910 peaks
    After polarity filter (positive): 803910 peaks
    After m/z and RT filters: 120 peaks
    After polarity filter (positive): 803910 peaks
    After m/z and RT filters: 120 peaks
    After chromatography filter (HILIC): 803910 peaks
    After chromatography filter (HILIC): 803910 peaks
    After polarity filter (positive): 803910 peaks
    After m/z and RT filters: 230 peaks
    After chromatography filter (HILIC): 803910 peaks
    After polarity filter (positive): 803910 peaks
    After m/z and RT filters: 230 peaks
    After chromatography filter (HILIC): 803910 peaks
    After polarity filter (positive): 803910 peaks
    After m/z and RT filters: 95 peaks
    After polarity filter (positive): 803910 peaks
    After m/z and RT filters: 95 peaks
    After chromatography filter (HILIC): 803910 peaks
    After polarity filter (positive): 803910 peaks
    After m/z and RT filters: 60 peaks
    After chromatography filter (HILIC): 803910 peaks
    After polarity filter (positive): 803910 peaks
    After m/z and RT filters: 60 peaks
    After chromatography filter (HILIC): 803910 peaks
    After chromatography filter (HILIC): 803910 peaks
    After polarity filter (positive): 803910 peaks
    After m/z and RT filters: 46 peaks
    After chromatography filter (HILIC): 803910 peaks
    After polarity filter (positive): 803910 peaks
    After m/z and RT filters: 46 peaks
    After chromatography filter (HILIC): 803910 peaks
    After polarity filter (positive): 803910 peaks
    After m/z and RT filters: 98 peaks
    After polarity filter (positive): 803910 peaks
    After m/z and RT filters: 98 peaks
    After chromatography filter (HILIC): 803910 peaks
    After polarity filter (positive): 803910 peaks
    After m/z and RT filters: 39 peaks
    After chromatography filter (HILIC): 803910 peaks
    After polarity filter (positive): 803910 peaks
    After m/z and RT filters: 39 peaks
    After chromatography filter (HILIC): 803910 peaks
    After chromatography filter (HILIC): 803910 peaks
    After polarity filter (positive): 803910 peaks
    After m/z and RT filters: 45 peaks
    After chromatography filter (HILIC): 803910 peaks
    After polarity filter (positive): 803910 peaks
    After m/z and RT filters: 45 peaks
    After chromatography filter (HILIC): 803910 peaks
    After polarity filter (positive): 803910 peaks
    After m/z and RT filters: 63 peaks
    After polarity filter (positive): 803910 peaks
    After m/z and RT filters: 63 peaks
    After chromatography filter (HILIC): 803910 peaks
    After polarity filter (positive): 803910 peaks
    After m/z and RT filters: 55 peaks
    After chromatography filter (HILIC): 803910 peaks
    After polarity filter (positive): 803910 peaks
    After m/z and RT filters: 55 peaks
    After chromatography filter (HILIC): 803910 peaks
    After chromatography filter (HILIC): 803910 peaks
    After polarity filter (positive): 803910 peaks
    After m/z and RT filters: 94 peaks
    After chromatography filter (HILIC): 803910 peaks
    After polarity filter (positive): 803910 peaks
    After m/z and RT filters: 94 peaks
    After chromatography filter (HILIC): 803910 peaks
    After polarity filter (positive): 803910 peaks
    After m/z and RT filters: 97 peaks
    After polarity filter (positive): 803910 peaks
    After m/z and RT filters: 97 peaks
    After chromatography filter (HILIC): 803910 peaks
    After polarity filter (positive): 803910 peaks
    After m/z and RT filters: 90 peaks
    After chromatography filter (HILIC): 803910 peaks
    After polarity filter (positive): 803910 peaks
    After m/z and RT filters: 90 peaks
    After chromatography filter (HILIC): 803910 peaks
    After chromatography filter (HILIC): 803910 peaks
    After polarity filter (positive): 803910 peaks
    After m/z and RT filters: 95 peaks
    After chromatography filter (HILIC): 803910 peaks
    After polarity filter (positive): 803910 peaks
    After m/z and RT filters: 95 peaks
    After chromatography filter (HILIC): 803910 peaks
    After polarity filter (positive): 803910 peaks
    After m/z and RT filters: 44 peaks

Processed 20 compounds, 20 had matches

Matching completed:
  Compounds with matches: 20/20
  Total compound-file matches: 40
  Mean m/z error: -0.21 ± 0.51 ppm
  Mean RT difference: 0.028 ± 0.119 min
Building RT alignment model...
Filtered out 2 matches by InChI Key.

RT Statistics Summary:
  Atlas RT range: 1.09 - 17.01 min
  Observed RT range (median): 1.25 - 17.14 min
  Mean RT difference (observed - atlas): 0.016 ± 0.109 min
Using 19 compounds with ≥1 observations (QC files) for modeling
Building polynomial model (degree 2)...

Model built successfully:
  Model type: Polynomial degree 2
  R² = 0.9998
  RMSE = 0.0820 min
  Max residual = 0.2197 min
  Equation: RT_corrected = 0.188479 + 0.946110 * RT_atlas + 0.002824 * RT_atlas^2

Compound RT Statistics:
    After polarity filter (positive): 803910 peaks
    After m/z and RT filters: 44 peaks

Processed 20 compounds, 20 had matches

Matching completed:
  Compounds with matches: 20/20
  Total compound-file matches: 40
  Mean m/z error: -0.21 ± 0.51 ppm
  Mean RT difference: 0.028 ± 0.119 min
Building RT alignment model...
Filtered out 2 matches by InChI Key.

RT Statistics Summary:
  Atlas RT range: 1.09 - 17.01 min
  Observed RT range (median): 1.25 - 17.14 min
  Mean RT difference (observed - atlas): 0.016 ± 0.109 min
Using 19 compounds with ≥1 observations (QC files) for modeling
Building polynomial model (degree 2)...

Model built successfully:
  Model type: Polynomial degree 2
  R² = 0.9998
  RMSE = 0.0820 min
  Max residual = 0.2197 min
  Equation: RT_corrected = 0.188479 + 0.946110 * RT_atlas + 0.002824 * RT_atlas^2

Compound RT Statistics:

,compound_name,inchi_key,ref_rt_peak,exp_rt_median,rt_diff_median,observation_count,exp_rt_std
0,"cystine (U - 13C, 15N)",LEVWYRKDKASIDU-OGYFDXEDSA-N,16.9043,17.003099,0.0988,2,0.0066
1,adenine (U - 15N),GFFGJBXGBJISGV-CIKZIQIKSA-N,2.6776,2.816400,0.1388,2,0.0213
2,"tyrosine (U - 13C, 15N)",OUYCCCASQSFEME-CMLFETTRSA-N,11.8552,11.751900,-0.1032,2,0.0209
3,ABMBA (unlabeled),LCMZECCEEOQWLQ-UHFFFAOYSA-N,1.0938,1.253400,0.1596,2,0.0001
4,"glutamic acid (U - 13C, 15N)",WHUUTDBJXJRKMK-UFLWJPECSA-N,15.9354,15.966100,0.0307,2,0.0090
5,guanine (U - 15N),UYTPUPDQBNUYGX-CIKZIQIKSA-N,6.2654,6.210600,-0.0548,2,0.0090
6,hypoxanthine (U - 15N),FDGQSTZJBFJUBT-NNZQUYKOSA-N,3.1030,3.149900,0.0469,2,0.0215
7,"arginine (U - 13C, 15N)",ODKSFYDXXFIFQN-GZYYCROJSA-N,16.9399,17.056601,0.1167,2,0.0058
8,"asparagine (U - 13C, 15N)",DCXYFEDJOCDNAF-FLEDYEEXSA-N,14.3681,14.318600,-0.0495,2,0.0003
9,"methionine (U - 13C, 15N)",FFEARJCKVFRZRR-XAFSXMPTSA-N,10.4410,10.409400,-0.0315,2,0.0075
10,"lysine (U - 13C, 15N)",KDXKERNSBIXSRK-JMKXWGMHSA-N,17.0113,17.136400,0.1251,2,0.0051
11,"valine (U - 13C, 15N)",KZSNJWFQEVHDMF-XAFSXMPTSA-N,11.1160,11.014900,-0.1011,2,0.0159
12,"phenylalanine (U - 13C, 15N)",COLNVLDHVKWLRT-CMLFETTRSA-N,8.9793,9.131300,0.1520,2,0.0028
13,"thymine (U - 13C, 15N)",RWQNBRDOKXIBIV-BNUYUSEDSA-N,1.2552,1.353900,0.0986,2,0.0003
14,"tryptophan (U - 13C, 15N)",QIVBCDIJIAJPQS-HNEHNLBWSA-N,10.1566,10.180700,0.0240,2,0.0109
15,inosine (U - 15N),UGQMRVRMYYASKQ-SHKQESLVSA-N,5.4342,5.197600,-0.2366,2,0.0412
16,"aspartic acid (U - 13C, 15N)",CKLJMWTZIZZHCS-NYTNKSBQSA-N,16.1304,16.169500,0.0391,2,0.0116
17,"alanine (U - 13C, 15N)",QNAYBMKLOCPYGJ-UVYXLFMMSA-N,13.4051,13.358000,-0.0471,2,0.0095
18,"threonine (U - 13C, 15N)",AYFVYJQAPQTCCC-KJQIOZMZSA-N,13.4896,13.384000,-0.1055,2,0.0094

Cloning target atlas and applying RT correction...
Retrieved atlas metadata for: HILIC Positive ISTD Default
Retrieved 65 compounds from main database for atlas: HILIC Positive ISTD Default (atl-raw-26bd6c4376d847259174fed1e95c329a)
Atlas chromatography: HILICZ, polarity: positive
RT alignment model saved to database with UID: rta-8e4ecf76759c4b02a076cecd08157407
Created RT-corrected atlas with 65 associations.

RT-corrected atlas created:
  Atlas UID: atl-rta-c171179d444543bd9206bbe09a22f7a0
  Atlas name: HILIC Positive ISTD Default (RT Corrected)
  RT alignment model UID: rta-8e4ecf76759c4b02a076cecd08157407
  Project database: /Users/BKieft/Metabolomics/metatlas2/data/test_data/projects/20250707_JGI_MS_510172_SedRhizVegOut_final_IQX_HILICZ_USHXG02519/20250707_JGI_MS_510172_SedRhizVegOut_final_IQX_HILICZ_USHXG02519.duckdb
  Correction summary:
    total_compounds: 65
    corrected_compounds: 65
    rt_alignment_uid: rta-8e4ecf76759c4b02a076cecd08157407
    corrected_atlas_uid: atl-rta-c171179d444543bd9206bbe09a22f7a0
    corrected_atlas_name: HILIC Positive ISTD Default (RT Corrected)
    mean_correction: 0.0025666344389370303
    std_correction: 0.06576401238114583
    min_correction: -0.06863330969195758
    max_correction: 0.13291269327641375
RT alignment model saved to database with UID: rta-8e4ecf76759c4b02a076cecd08157407
Created RT-corrected atlas with 65 associations.

RT-corrected atlas created:
  Atlas UID: atl-rta-c171179d444543bd9206bbe09a22f7a0
  Atlas name: HILIC Positive ISTD Default (RT Corrected)
  RT alignment model UID: rta-8e4ecf76759c4b02a076cecd08157407
  Project database: /Users/BKieft/Metabolomics/metatlas2/data/test_data/projects/20250707_JGI_MS_510172_SedRhizVegOut_final_IQX_HILICZ_USHXG02519/20250707_JGI_MS_510172_SedRhizVegOut_final_IQX_HILICZ_USHXG02519.duckdb
  Correction summary:
    total_compounds: 65
    corrected_compounds: 65
    rt_alignment_uid: rta-8e4ecf76759c4b02a076cecd08157407
    corrected_atlas_uid: atl-rta-c171179d444543bd9206bbe09a22f7a0
    corrected_atlas_name: HILIC Positive ISTD Default (RT Corrected)
    mean_correction: 0.0025666344389370303
    std_correction: 0.06576401238114583
    min_correction: -0.06863330969195758
    max_correction: 0.13291269327641375

In [12]:
reference_df = ldt.load_msms_refs_file(CONFIG['paths']['msms_refs'])

Loading reference spectra from /Users/BKieft/Metabolomics/metatlas2/data/databases/msms_refs/msms_refs_no_inosine15n.tab...
No valid reference spectra found

In [13]:
df = pd.read_csv(CONFIG['paths']['msms_refs'], sep='\t')

In [14]:
df.head()

,,,,,,,,,,,,,,permanent_index,database,unique_id,Unnamed: 3
68,metatlas,5dc5bc5626f84c69b79085e40a5ca45a,ABMBA,"[[75.61710, 104.05100, 175.42100, 183.97700, 210.96400, 211.97100, 212.95800, 212.97700, 228.97400, 229.23500, 229.98200, 230.97200], [2062.00000, 2465.00000, 2034.00000, 11473.00000, 9923.00000, 666792.00000, 4027.00000, 21022.00000, 143835.00000, 5046.00000, 69795.00000, 151282.00000]]",4.0,229.9810,positive,NaN,cid,NaN,NaN,NaN,C8H8BrNO2,228.973841,LCMZECCEEOQWLQ-UHFFFAOYSA-N,"InChI=1S/C8H8BrNO2/c1-4-2-5(8(11)12)7(10)6(9)3-4/h2-3H,10H2,1H3,(H,11,12)",NaN
166,metatlas,6e8883f458c548c1b5ed51654fa71a3a,ABMBA,"[[50.25710, 56.97980, 64.98520, 70.23330, 74.75040, 78.91750, 83.05550, 89.71420, 183.97600, 191.13600, 212.86700, 214.30800, 227.94400, 227.96700, 228.96900], [49223.00000, 51385.00000, 52217.00000, 60027.00000, 60247.00000, 35644100.00000, 56862.00000, 57079.00000, 867456.00000, 55427.00000, 85170.00000, 65089.00000, 114411.00000, 2857580.00000, 72178.00000]]",4.0,227.9670,negative,NaN,cid,NaN,NaN,NaN,C8H8BrNO2,228.973841,LCMZECCEEOQWLQ-UHFFFAOYSA-N,"InChI=1S/C8H8BrNO2/c1-4-2-5(8(11)12)7(10)6(9)3-4/h2-3H,10H2,1H3,(H,11,12)",NaN
216192,metatlas,istdv7c4913851cc5c418cb7612090d5f4f21e,ABMBA,"[[51.02288, 52.03081, 53.03853, 58.06506, 65.03854, 67.05424, 73.51794, 74.86793, 75.10487, 77.03855, 78.03380, 78.04636, 95.04909, 96.04441, 102.03372, 103.04166, 104.04944, 105.04470, 105.05289, 105.05717, 115.26279, 118.06503, 122.06004, 130.03981, 140.60715, 144.22331, 145.07593, 151.06288, 156.96457, 182.96326, 183.95808, 183.97560, 184.96655, 206.22324, 211.97050, 212.16415, 212.96053, 212.97278, 225.00266, 229.97984, 230.24844, 230.97113], [35249.13281, 4836.63330, 34103.06641, 6292.85889, 20012.89062, 3319.56396, 3526.23584, 3354.40942, 3721.81958, 46376.94531, 5362.40771, 73571.36719, 47505.48828, 6596.74707, 6648.10547, 6480.33789, 142472.21875, 29794.00000, 5071.69238, 48048.02344, 3279.05127, 7635.12842, 14636.56348, 7697.88037, 3542.01709, 3708.28271, 9330.17773, 9168.37402, 9658.37793, 9261.20215, 10323.70703, 143735.79688, 4027.19214, 3439.80957, 819399.50000, 3678.39087, 10824.97656, 4634.33301, 5728.95801, 81078.92188, 8182.21729, 68314.05469]]",4.0,229.9811,positive,[M+H]+,HCD,absolute-102040,EXP120B,Orbitrap,C8H8BrNO2,228.973841,LCMZECCEEOQWLQ-UHFFFAOYSA-N,"InChI=1S/C8H8BrNO2/c1-4-2-5(8(11)12)7(10)6(9)3-4/h2-3H,10H2,1H3,(H,11,12)",Cc1cc(Br)c(N)c(C(=O)O)c1
216193,metatlas,istdv77a645ff92123412188306f86f610906c,ABMBA,"[[50.01511, 51.02293, 51.02447, 51.71570, 52.03078, 53.03861, 54.03392, 58.06514, 59.04918, 62.01525, 63.02298, 65.02599, 65.03863, 66.14971, 73.30192, 73.95960, 75.02296, 76.01830, 76.02640, 76.03063, 77.03860, 78.03391, 78.04643, 79.04158, 80.26266, 95.03673, 95.04919, 95.53805, 96.04451, 102.03390, 103.04183, 104.04567, 104.04951, 105.04475, 105.05305, 105.05737, 105.73785, 116.93370, 118.06510, 122.06007, 130.03990, 133.46303, 145.07617, 145.55469, 156.96487, 169.47971, 182.96341, 183.95992, 183.97578, 183.98651, 184.96545, 201.98721, 211.97064, 212.96092, 224.12683, 229.97670, 230.97124], [52889.90234, 198771.28125, 8568.63574, 4379.77002, 56367.76562, 34005.90234, 8106.91650, 5812.30420, 7007.83887, 7674.06787, 19912.97070, 7049.20947, 45765.05859, 4404.29297, 4502.98438, 4323.03467, 8922.90332, 11569.60059, 7373.13672, 4343.56494, 65951.10938, 9916.03809, 131516.23438, 8474.78711, 4275.28125, 4305.35889, 88926.21094, 4274.78662, 20136.62695, 8803.81543, 4799.75293, 4272.79443, 184066.06250, 55146.16406, 5096.05762, 62823.09375, 4732.05859, 10118.04297, 6263.53906, 18901.17773, 7248.29492, 4101.55322, 19523.86133, 4151.77148, 9138.94238, 4291.83643, 5621.06055, 6072.56006, 239606.12500, 4780.20264, 4997.38428, 6398.62744, 388608.53125, 7372.81885, 4573.78027, 8160.61377, 16577.61523]]",4.0,229.9811,positive,[M+H]+,HCD,absolute-205060,EXP120B,Orbitrap,C8H8BrNO2,228.973841,LCMZECCEEOQWLQ-UHFFFAOYSA-N,"InChI=1S/C8H8BrNO2/c1-4-2-5(8(11)12)7(10)6(9)3-4/h2-3H,10H2,1H3,(H,11,12)",Cc1cc(Br)c(N)c(C(=O)O)c1
216194,metatlas,istdv7f5e5f4bbc37c495c9af84e24bd3aefb1,ABMBA,"[[52.99299, 53.03949, 58.06504, 64.68795, 68.23689, 68.36103, 80.43700, 84.82559, 90.12204, 104.04949, 104.55593, 105.05744, 136.73798, 151.06267, 177.94000, 183.97563, 211.13062, 211.94403, 211.94966, 211.97064, 211.99715, 212.16429, 212.96088, 212.97372, 217.86977, 225.96384, 229.94716, 229.98109, 230.11882, 230.13934, 230.24753, 230.97133, 230.98547], [6122.33350, 3026.51660, 3364.24365, 3155.86890, 3462.24097, 3385.94360, 3236.32056, 3493.11890, 3754.03735, 10745.45703, 3226.53149, 3573.74219, 3982.19971, 12536.66504, 3729.24658, 78916.15625, 3816.52856, 13162.23438, 6638.35547, 1882670.00000, 13034.00488, 4640.86328, 25937.29883, 9050.51270, 3672.51050, 3719.99268, 7647.78174, 442128.87500, 4958.26123, 6200.88574, 18885.03516, 118160.95312, 8804.16895]]",4.0,229.9811,positive,[M+H]+,HCD,normalized-102040,EXP120B,Orbitrap,C8H8BrNO2,228.973841,LCMZECCEEOQWLQ-UHFFFAOYSA-N,"InChI=1S/C8H8BrNO2/c1-4-2-5(8(11)12)7(10)6(9)3-4/h2-3H,10H2,1H3,(H,11,12)",Cc1cc(Br)c(N)c(C(=O)O)c1

In [8]:
if new_analysis is True:
    atlas_df_ft, experiment_data = tga.run_targeted_analysis_workflow(
        PROJECT_DB_PATH, ANALYSIS_ATLAS_UID, CONFIG
    )
    
    gui = tgi.create_gui(experiment_data, atlas_df_ft, CONFIG)
    
    summary = dc.get_summary_dataframe(experiment_data)
    display(summary.head())

display(gui)

Setting up targeted analysis...
Loading target atlas...
Retrieved 65 compounds from project database for atlas: HILIC Positive ISTD Default (RT Corrected) (atl-rta-c171179d444543bd9206bbe09a22f7a0)
Atlas chromatography: HILICZ, polarity: positive
RT-corrected atlas detected with experimental data
Enriched 65 compounds with metadata from main database
Created Atlas dataframe with 65 compounds
Loading experimental files from project database...
Found 6 experimental files in database
Found 6 experimental files
Preparing inputs for feature extraction...
Created 6 input dictionaries
Extracting EIC and MS2 data...
Loading reference spectra from /Users/BKieft/Metabolomics/metatlas2/data/databases/msms_refs/msms_refs_no_inosine15n.tab...
No valid reference spectra found
Loaded 0 reference spectra for MS2 matching
Extracting data from 6 files...
Using parallel processing with 6 workers...

Processing files in parallel:   0%|          | 0/6 [00:00<?, ?it/s]

  Error in parallel processing: 'inchi_key'
  Error in parallel processing: 'inchi_key'
  Error in parallel processing: 'inchi_key'
  Error in parallel processing: 'inchi_key'

Extraction complete:
  Total compounds: 54
  Compounds with EIC data: 54
  Compounds with MS2 data: 0
  Compounds with MS2 hits: 0
  Total EIC traces: 85
  Total MS2 spectra: 0
Converting experiment data to GUI format...
Converted 54 compounds to GUI format

Extraction complete:
  Total compounds: 54
  Compounds with EIC data: 54
  Compounds with MS2 data: 0
  Compounds with MS2 hits: 0
  Total EIC traces: 85
  Total MS2 spectra: 0
Converting experiment data to GUI format...
Converted 54 compounds to GUI format

,inchi_key,eic_files,ms2_files,total_spectra,spectra_with_hits,best_eic_intensity,best_eic_rt_error,best_eic_ppm_error,best_hit_score,best_hit_database,average_hit_score
0,OVRNDRQMDRJTHS-ZEUBEQSHSA-N,2,0,0,0,7.393078e+05,0.194254,0.367020,0,,0.0
1,GFFGJBXGBJISGV-CIKZIQIKSA-N,2,0,0,0,5.601356e+08,0.074504,0.352657,0,,0.0
2,GFFGJBXGBJISGV-UHFFFAOYSA-N,2,0,0,0,1.485015e+05,0.055486,0.354238,0,,0.0
3,QNAYBMKLOCPYGJ-REOHCLBHSA-N,2,0,0,0,2.703556e+04,-0.103926,0.288588,0,,0.0
4,ODKSFYDXXFIFQN-GZYYCROJSA-N,2,0,0,0,1.883878e+07,0.006259,0.206889,0,,0.0

VBox(children=(HBox(children=(HBox(children=(Button(button_style='primary', description='◀ Prev', layout=Layou…

In [9]:
if new_analysis is True:
    plot_data = tga.convert_experiment_data_to_gui_format(experiment_data, atlas_df_ft)
    post_analysis_atlas_uid = tga.create_post_analysis_atlas(PROJECT_DB_PATH, ANALYSIS_ATLAS_UID, plot_data, CONFIG)
    targeted_analysis_uid = dbi.deposit_targeted_analysis_from_plot_data(atlas_df_ft, PROJECT_DB_PATH, plot_data, post_analysis_atlas_uid, PROJECT_NAME)
    comprehensive_report = dbi.generate_comprehensive_targeted_analysis_report(PROJECT_DB_PATH, CONFIG, targeted_analysis_uid, atlas_df_ft, REPORT_PATH)

Converting experiment data to GUI format...
Converted 54 compounds to GUI format
Retrieved 65 compounds from project database for atlas: HILIC Positive ISTD Default (RT Corrected) (atl-rta-c171179d444543bd9206bbe09a22f7a0)
Atlas chromatography: HILICZ, polarity: positive
RT-corrected atlas detected with experimental data
Enriched 65 compounds with metadata from main database
Cloned and modified atlas atl-rta-c171179d444543bd9206bbe09a22f7a0 from /Users/BKieft/Metabolomics/metatlas2/data/test_data/projects/20250707_JGI_MS_510172_SedRhizVegOut_final_IQX_HILICZ_USHXG02519/20250707_JGI_MS_510172_SedRhizVegOut_final_IQX_HILICZ_USHXG02519.duckdb to new atlas atl-tga-18783b92acad4a74a6e6ddee66567625 in /Users/BKieft/Metabolomics/metatlas2/data/test_data/projects/20250707_JGI_MS_510172_SedRhizVegOut_final_IQX_HILICZ_USHXG02519/20250707_JGI_MS_510172_SedRhizVegOut_final_IQX_HILICZ_USHXG02519.duckdb
Inserted 54 rows into targeted_analysis table with analysis_uid tga-25874615ba7c4c55b08ad9137d9d0489.
Enhanced MS2 selection: reference_hits=0, intensity_based=54
Generating comprehensive report for 54 compounds...
Generating comprehensive report for 54 compounds...

Processing compounds:   0%|          | 0/54 [00:00<?, ?it/s]

Report saved to /Users/BKieft/Downloads/20250707_JGI_MS_510172_SedRhizVegOut_final_IQX_HILICZ_USHXG02519_comprehensive_report.xlsx

In [10]:
# NEW: Example of using class-based filtering and analysis
if new_analysis is True:
    print("\n=== Class-Based Analysis Examples ===")
    
    # Filter compounds by RT error
    good_rt_compounds = dc.filter_compounds_by_rt_error(experiment_data, max_rt_error=0.5)
    print(f"Compounds with RT error ≤ 0.5 min: {len(good_rt_compounds)}")
    
    # Filter compounds by MS2 score
    high_score_compounds = dc.filter_compounds_by_score(experiment_data, min_score=0.7)
    print(f"Compounds with MS2 score ≥ 0.7: {len(high_score_compounds)}")
    
    # Get compounds with both good RT and MS2 data
    both_criteria = [c for c in good_rt_compounds if c in high_score_compounds]
    print(f"Compounds meeting both criteria: {len(both_criteria)}")
    
    # Access individual compound data
    if experiment_data.compounds:
        example_inchi = list(experiment_data.compounds.keys())[0]
        example_compound = experiment_data.get_compound(example_inchi)
        print(f"\nExample compound: {example_inchi}")
        print(f"  EIC files: {len(example_compound.files_with_eic_data)}")
        print(f"  MS2 files: {len(example_compound.files_with_ms2_data)}")
        print(f"  Spectra with hits: {len(example_compound.get_spectra_with_hits())}")
        
        if example_compound.best_eic_by_intensity:
            best_eic = example_compound.best_eic_by_intensity
            print(f"  Best EIC: {best_eic.filename} (intensity: {best_eic.intensity_peak:.0f})")
        
        if example_compound.best_ms2_by_score:
            best_ms2 = example_compound.best_ms2_by_score
            print(f"  Best MS2: {best_ms2.filename} (score: {best_ms2.best_hit.score:.3f})")

=== Class-Based Analysis Examples ===
Compounds with RT error ≤ 0.5 min: 54
Compounds with MS2 score ≥ 0.7: 0
Compounds meeting both criteria: 0

Example compound: OVRNDRQMDRJTHS-ZEUBEQSHSA-N
  EIC files: 2
  MS2 files: 0
  Spectra with hits: 0
  Best EIC: 20250707_JGI_MS_510172_SedRhizVegOut_final_IQX_HILICZ_USHXG02519_FPS_MS1_28_Spring-VSp_2_Rg70to1050-CE102040norm-veg-core-ISTD_Run31.h5 (intensity: 739308)